.SILENT:


default:
	type Makefile

quiz3-banks:
	@echo Building quiz 3 question banks
	text2qti quiz3-normalization-blooms-2.md
	text2qti quiz3-normalization-blooms-3.md
	text2qti quiz3-normalization-blooms-4.md
	text2qti quiz3-normalization-blooms-5.md

q2 : quiz3-banks
