.SILENT:


default:
	type Makefile

quiz2-banks:
	@echo Building quiz 2 question banks
	text2qti quiz2-bank-relations-blooms-2.md
	text2qti quiz2-bank-relations-blooms-3.md
	text2qti quiz2-bank-relations-blooms-4.md
	text2qti quiz2-bank-relations-blooms-5.md

q2 : quiz2-banks
