./add-mysql-user-and-db.sh -u sp25_acostas -p Shout4_acostas_joY
./add-mysql-user-and-db.sh -u sp25_adepojus -p Shout4_adepojus_joY
./add-mysql-user-and-db.sh -u sp25_akeredolunr -p Shout4_akeredolunr_joY
./add-mysql-user-and-db.sh -u sp25_amjadm2 -p Shout4_amjadm2_joY
./add-mysql-user-and-db.sh -u sp25_arbietot -p Shout4_arbietot_joY
./add-mysql-user-and-db.sh -u sp25_ayanoug -p Shout4_ayanoug_joY
./add-mysql-user-and-db.sh -u sp25_bahlouly -p Shout4_bahlouly_joY
./add-mysql-user-and-db.sh -u sp25_behboudin -p Shout4_behboudin_joY
./add-mysql-user-and-db.sh -u sp25_berdeguezcm -p Shout4_berdeguezcm_joY
./add-mysql-user-and-db.sh -u sp25_biguvubs -p Shout4_biguvubs_joY
./add-mysql-user-and-db.sh -u sp25_biguvuhs -p Shout4_biguvuhs_joY
./add-mysql-user-and-db.sh -u sp25_bohnc -p Shout4_bohnc_joY
./add-mysql-user-and-db.sh -u sp25_bottuaj2 -p Shout4_bottuaj2_joY
./add-mysql-user-and-db.sh -u sp25_boyettja -p Shout4_boyettja_joY
./add-mysql-user-and-db.sh -u sp25_chalises2 -p Shout4_chalises2_joY
./add-mysql-user-and-db.sh -u sp25_chavdarovig -p Shout4_chavdarovig_joY
./add-mysql-user-and-db.sh -u sp25_chavezci -p Shout4_chavezci_joY
./add-mysql-user-and-db.sh -u sp25_clarkl3 -p Shout4_clarkl3_joY
./add-mysql-user-and-db.sh -u sp25_colonca2 -p Shout4_colonca2_joY
./add-mysql-user-and-db.sh -u sp25_corcorantj -p Shout4_corcorantj_joY
./add-mysql-user-and-db.sh -u sp25_dsouzanb -p Shout4_dsouzanb_joY
./add-mysql-user-and-db.sh -u sp25_dangct3 -p Shout4_dangct3_joY
./add-mysql-user-and-db.sh -u sp25_dannoufja -p Shout4_dannoufja_joY
./add-mysql-user-and-db.sh -u sp25_davisar -p Shout4_davisar_joY
./add-mysql-user-and-db.sh -u sp25_davispn6 -p Shout4_davispn6_joY
./add-mysql-user-and-db.sh -u sp25_delapenajd -p Shout4_delapenajd_joY
./add-mysql-user-and-db.sh -u sp25_dhanaliwalas -p Shout4_dhanaliwalas_joY
./add-mysql-user-and-db.sh -u sp25_dhorajiap -p Shout4_dhorajiap_joY
./add-mysql-user-and-db.sh -u sp25_duncand3 -p Shout4_duncand3_joY
./add-mysql-user-and-db.sh -u sp25_duncanrm2 -p Shout4_duncanrm2_joY
./add-mysql-user-and-db.sh -u sp25_elnafemr -p Shout4_elnafemr_joY
./add-mysql-user-and-db.sh -u sp25_essexjg -p Shout4_essexjg_joY
./add-mysql-user-and-db.sh -u sp25_faircw -p Shout4_faircw_joY
./add-mysql-user-and-db.sh -u sp25_fergusonba -p Shout4_fergusonba_joY
./add-mysql-user-and-db.sh -u sp25_ganeshr -p Shout4_ganeshr_joY
./add-mysql-user-and-db.sh -u sp25_ginthersg -p Shout4_ginthersg_joY
./add-mysql-user-and-db.sh -u sp25_glassal -p Shout4_glassal_joY
./add-mysql-user-and-db.sh -u sp25_govila -p Shout4_govila_joY
./add-mysql-user-and-db.sh -u sp25_grayjl3 -p Shout4_grayjl3_joY
./add-mysql-user-and-db.sh -u sp25_hayt2 -p Shout4_hayt2_joY
./add-mysql-user-and-db.sh -u sp25_hendersonks -p Shout4_hendersonks_joY
./add-mysql-user-and-db.sh -u sp25_henrygm -p Shout4_henrygm_joY
./add-mysql-user-and-db.sh -u sp25_hicksm5 -p Shout4_hicksm5_joY
./add-mysql-user-and-db.sh -u sp25_jalili -p Shout4_jalili_joY
./add-mysql-user-and-db.sh -u sp25_jamess7 -p Shout4_jamess7_joY
./add-mysql-user-and-db.sh -u sp25_jeffreym2 -p Shout4_jeffreym2_joY
./add-mysql-user-and-db.sh -u sp25_joneskl12 -p Shout4_joneskl12_joY
./add-mysql-user-and-db.sh -u sp25_khanr15 -p Shout4_khanr15_joY
./add-mysql-user-and-db.sh -u sp25_leecl5 -p Shout4_leecl5_joY
./add-mysql-user-and-db.sh -u sp25_luchsingerkr -p Shout4_luchsingerkr_joY
./add-mysql-user-and-db.sh -u sp25_maazouzrm -p Shout4_maazouzrm_joY
./add-mysql-user-and-db.sh -u sp25_macklr -p Shout4_macklr_joY
./add-mysql-user-and-db.sh -u sp25_maliki3 -p Shout4_maliki3_joY
./add-mysql-user-and-db.sh -u sp25_marandinalc -p Shout4_marandinalc_joY
./add-mysql-user-and-db.sh -u sp25_meersohnf -p Shout4_meersohnf_joY
./add-mysql-user-and-db.sh -u sp25_menendezrd -p Shout4_menendezrd_joY
./add-mysql-user-and-db.sh -u sp25_mensahko -p Shout4_mensahko_joY
./add-mysql-user-and-db.sh -u sp25_minora3 -p Shout4_minora3_joY
./add-mysql-user-and-db.sh -u sp25_mohapatraa -p Shout4_mohapatraa_joY
./add-mysql-user-and-db.sh -u sp25_nalavadeaa -p Shout4_nalavadeaa_joY
./add-mysql-user-and-db.sh -u sp25_onyedekek -p Shout4_onyedekek_joY
./add-mysql-user-and-db.sh -u sp25_othmanb -p Shout4_othmanb_joY
./add-mysql-user-and-db.sh -u sp25_pantigozocam -p Shout4_pantigozocam_joY
./add-mysql-user-and-db.sh -u sp25_phuthongthiak -p Shout4_phuthongthiak_joY
./add-mysql-user-and-db.sh -u sp25_pomeroyjd -p Shout4_pomeroyjd_joY
./add-mysql-user-and-db.sh -u sp25_rahmana17 -p Shout4_rahmana17_joY
./add-mysql-user-and-db.sh -u sp25_raphaelke -p Shout4_raphaelke_joY
./add-mysql-user-and-db.sh -u sp25_qbrentz -p Shout4_qbrentz_joY
./add-mysql-user-and-db.sh -u sp25_riveradr -p Shout4_riveradr_joY
./add-mysql-user-and-db.sh -u sp25_robertj -p Shout4_robertj_joY
./add-mysql-user-and-db.sh -u sp25_rutanj -p Shout4_rutanj_joY
./add-mysql-user-and-db.sh -u sp25_salihas -p Shout4_salihas_joY
./add-mysql-user-and-db.sh -u sp25_sapptc -p Shout4_sapptc_joY
./add-mysql-user-and-db.sh -u sp25_sarkermm -p Shout4_sarkermm_joY
./add-mysql-user-and-db.sh -u sp25_selbdm -p Shout4_selbdm_joY
./add-mysql-user-and-db.sh -u sp25_siddiqiso2 -p Shout4_siddiqiso2_joY
./add-mysql-user-and-db.sh -u sp25_singhj21 -p Shout4_singhj21_joY
./add-mysql-user-and-db.sh -u sp25_skeetej -p Shout4_skeetej_joY
./add-mysql-user-and-db.sh -u sp25_smithaa9 -p Shout4_smithaa9_joY
./add-mysql-user-and-db.sh -u sp25_stephensj4 -p Shout4_stephensj4_joY
./add-mysql-user-and-db.sh -u sp25_strobelb2 -p Shout4_strobelb2_joY
./add-mysql-user-and-db.sh -u sp25_taylors -p Shout4_taylors_joY
./add-mysql-user-and-db.sh -u sp25_tejedamr -p Shout4_tejedamr_joY
./add-mysql-user-and-db.sh -u sp25_thompsone7 -p Shout4_thompsone7_joY
./add-mysql-user-and-db.sh -u sp25_torresc6 -p Shout4_torresc6_joY
./add-mysql-user-and-db.sh -u sp25_trand15 -p Shout4_trand15_joY
./add-mysql-user-and-db.sh -u sp25_trant14 -p Shout4_trant14_joY
./add-mysql-user-and-db.sh -u sp25_upadhyaya -p Shout4_upadhyaya_joY
./add-mysql-user-and-db.sh -u sp25_vangipurapus -p Shout4_vangipurapus_joY
./add-mysql-user-and-db.sh -u sp25_veasnadt -p Shout4_veasnadt_joY
./add-mysql-user-and-db.sh -u sp25_venkateswarkm -p Shout4_venkateswarkm_joY
./add-mysql-user-and-db.sh -u sp25_viadolm -p Shout4_viadolm_joY
./add-mysql-user-and-db.sh -u sp25_weaverge -p Shout4_weaverge_joY
./add-mysql-user-and-db.sh -u sp25_wellsmh -p Shout4_wellsmh_joY
./add-mysql-user-and-db.sh -u sp25_wilkinsonla -p Shout4_wilkinsonla_joY
./add-mysql-user-and-db.sh -u sp25_williamsc45 -p Shout4_williamsc45_joY
./add-mysql-user-and-db.sh -u sp25_winsorlm -p Shout4_winsorlm_joY
./add-mysql-user-and-db.sh -u sp25_yahayay -p Shout4_yahayay_joY
./add-mysql-user-and-db.sh -u sp25_yazbeckn -p Shout4_yazbeckn_joY
