---
date: last-modified
title: Week 6 - Details
---

```{python}
#| echo: false
this_file = "week-00-details.qmd"
```

<!-- overview-block-begin -->

<p class="lead">Redundant content is a challenge in databases.  Normalization describes the way we minimize duplicate and redundent content.</p>
    
<!-- overview-block-end -->

<!-- deliverables-block-begin -->
#### Things to do this week


[Discussion 3 - Normal forms](https://virginiacommonwealth.instructure.com/courses/113813/assignments/1075915) is a challenging discussion because you need to know about normalization to get started. I HIGHLY recommend that you watch the *Normal Forms* video in the resources.

<!-- deliverables-block-end -->

<!-- resources-block-begin -->
#### Notes on the Resources

Review ALL the resources above. Here are some additional notes:
    
[Normal Forms](https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-week-6-normal-forms-3) is probably the *MOST IMPORTANT* video you can watch this week. It very cleanly describes normal forms and why they're important.  Watch this *before* you tackle the discussion assignment.


[BCNF](https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-week-6-bcnf-3) is another video from Decomplexify (the author of the normal forms video).  This video describes *Boyce-Codd Normal Form* or *BCNF*.


[Keys and more keys](https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-week-6-keys-and-more-keys-3) provides an overview of *all* the different kinds of database keys.


[Denormalization](https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-week-6-denormalization-3) is a change of pace.  While we've been spending all of our time *normalizing* databases, sometime we need to *denormalize* them!  Check it out!

<!-- resources-block-end -->