---
title: Resource - SAVE YOU HOURS&trade;
---

```{python}
#| echo: false
#| output: asis

# For pages, the "title" in the YAML will be used as the title in Canvas.

from cnvsapi.designplus import dp_banner2_from_qmd
__file__ = "save-you-hours.qmd"

print( dp_banner2_from_qmd( __file__ ))
```
::: {class="lead"}
I regularly get the same questions over and over. I assembled these suggestions in one place
designed to **SAVE YOU HOURS™!**
:::

**ALL HOMEWORKS ARE ACCEPTED LATE!** - You learn databases by doing databases. I want you to do all the homework so you
learn databases! I realize that life happens - so when it does *RELAX.* Do what
you need to do and then *FINISH YOUR HOMEWORK!* Don't get too far behind; it's hard to catch up!

*Sheesh, Dr. Leonard, what are you thinking?* I'm glad you asked! [This is what I'm thinking!](https://www.frontiersin.org/journals/education/articles/10.3389/feduc.2024.1324506/full)

**LOOK AT ALL THE FILES IN THE HOMEWORK SCAFFOLDS!**  -
I don't drop files into the scaffold GitHub repos to take up room. The support files
(anything not named `report.qmd` or `report.html`) often provide very useful examples for
completing the homework. Why reinvent the wheel? Investigate what I provide, and you may
find answers to all your questions and *SAVE YOU HOURS&trade;.*

**WATCH THE LECTURES!**  -
It's clear from both the Canvas statistics AND the questions I receive on the weekends that over
half of you are not watching the lectures. [Try it - you'll like it!](https://www.youtube.com/watch?v=9qdfMYFl0Ic){target="_blank" class="inline_disabled" rel="noopener"}
In each lecture, I spend time at the beginning talking about the homework assignments and comment on questions 
I've been receiving from others in the class. Heck, I may even provide a tip or trick that can *SAVE YOU HOURS™.*

The lectures are organized and follow a specific rhythm - on the first slide I provide announcements
AND a list of topics for the lecture. Each topic matches slide separators in the video - you can
fast-forward ahead to find where the topic starts. I try to discuss homeworks at the beginning to make the conversation easier to find.

**CHECK OUT THE RESOURCES!** -
Each week I spend a lot of time curating *the perfect* resources for sharing on the weekly
frontpage. My goal is to provide informative and sometimes entertaining sites and videos that
will complement the assignments and lectures. Please spend a few minutes at least scanning
them. Again, you might find a tip or trick that can *SAVE YOU HOURS™* on the homework.

**READ THE ANNOUNCEMENTS!** -
Please, please, please *READ* the announcements! If you encounter an issue with the
homework, *FIRST* look at the announcements! My fingers are tired from telling people on
Saturday and Sunday nights that the usernames and database names changed to
*LOWERCASE!* Your emails to me suggested that you'd already spent hours trying to get
the database to work. A quick read of the announcements may *SAVE YOU HOURS™!*
