
# Creating and using a database

## Review

### DDL file

* commands to create the database
* DROP TABLE, CREATE TABLE, INSERT INTO

### Data constraints

* attributes to ensure that only good data gets into the database
* Data types: INT, DATE, VARCHAR(255), VARCHAR(4096)
* Data attributes:  NOT NULL, DEFAULT 

### Integrity constraints

* attributes to ensure that everything remains related properly
* PRIMARY KEY, FOREIGN KEY: wiring between tables
* UNIQUE: integrity across records

## Integrity constraints: Potential issues

QUESTION: what happens when a record mentioned in a foreign key is deleted?

EXAMPLE: what happens when we delete a SKILL and the skill is referenced in PEOPLESKILLS?

New statements:

* FOREIGN KEY ... **ON UPDATE**  ... **ON DELETE**

## Integrity constraints - [Foreign Keys](https://www.mysqltutorial.org/mysql-foreign-key/)

MySQL has five reference options: CASCADE, SET NULL, NO ACTION, RESTRICT, and SET DEFAULT.

CASCADE
: if a row from the parent table is deleted or updated, the values of the matching rows in the child table are automatically deleted or updated.

SET NULL
: if a row from the parent table is deleted or updated, the values of the foreign key column (or columns) in the child table are set to NULL.

RESTRICT
: if a row from the parent table has a matching row in the child table, MySQL rejects deleting or updating rows in the parent table.

NO ACTION
: is the same as RESTRICT.

SET DEFAULT
: is recognized by the MySQL parser. However, this action is rejected by both InnoDB and NDB tables.

## Homework 7

### Link to the description

<https://virginiacommonwealth.instructure.com/courses/85746/assignments/725428>

<p>&nbsp;</p>

### Demonstration (continues)

In-class start walk-through of homework 7.

