# Homework 2 - Fall 2024

## Homework 2 - Fall 2024
:::: {.columns}

::: {.column width="50%"}
### Overview

* Homeworks 1 and 2 focus on ER diagrams
* Homework 2 offers practice creating ER diagrams.
* [Link to Homework 2](https://virginiacommonwealth.instructure.com/courses/105097/assignments/966518)

### General homework workflow
* *Same as homework 1!*
* Download assignment repository
* Edit files using VS code
* Commit and push changes to GITHUB
    * Submit HTML to Canvas
    * Submit repo to Gradescope

### Safety Tips
* [Watch the lecture!!!](https://virginiacommonwealth.instructure.com/courses/105097/pages/lecture-4-video-9){target="_blank"}
* Read the QMD and MD files in the REPO!

:::
::: {.column width="50%"}
### Notes
* The focus of this assignment creating ER diagrams in Quarto using mermaid and graphviz.
* Please allow plenty of time!
* Don't get frustrated.  Use *Discord* and *ChatGPT* to get help.
* Use the command line to render, and commit.

### Worked example: Comic Book Management System  
Consider a comic book store that wants to manage comic books, authors, and customers. Each comic book has a comic ID, title, genre, and publication date. Authors have an author ID, name, and biography. Customers have a customer ID, name, and contact information. A comic book can be written by multiple authors, and each author can contribute to multiple comic books. A customer can purchase multiple comic books, and each purchase involves a single customer and one or more comic books. Purchases have a purchase ID, date, and total amount.

:::
::::

