# MySQL Passwords

## How do I change my password?

You actually have *TWO different* mysql accounts: one for local connections and a second for remote connections.  

* Your remote and local accounts are granted permission to access your `hr`, `user` and `team` databases.

* Your local and remote accounts were assigned the same password

* Logins are managed transparently so it looks like only one account!

* You can only change your password through your local or remote connections.

Unless you have `CREATE USER` permissions you'll not be able to alter one user from another connection.

## How do I change my password?

Here is the one SQL command:

<center>***ALTER USER CURRENT_USER IDENTIFIED BY 'Shout4_jdleonard_JOY';***</center>
<p>&nbsp;</p>

:::: {.columns}
::: {.column width="50%"}
### Local connections

* Used when you connect via PhpMyAdmin or when you 
log to the server directly via SSH.

* Username: '24fa_jdleonard'@'localhost'

* You can only change this password from `phpmyadmin` or from the command line on the server itself.

:::
::: {.column width="50%"}
### Remote connections

* Used when you connect through your laptop (remotely) using vscode or a language like python.

* Username: '24fa_jdleonard'@'%'

* You can only change this through VS Code connection or
through your application program.

:::
::::



