---
title: Resource - SAVE YOU HOURS&trade;
---

fs<p>I regularly get the same questions over and over. I assembled these suggestions in one place designed to SAVE YOU HOURS<span>&trade;!</span></p>
<p><span><strong>ALL HOMEWORKS ARE ACCEPTED LATE! </strong>You learn databases by doing databases. I want you to do all the homework so you learn databases! I realize that life happens - so when it does RELAX.&nbsp; Do what you need to do and then FINISH YOUR HOMEWORK!&nbsp; Don't get too far behind, it's hard to catch up!&nbsp; (Sheesh, Dr Leonard what were thinking?; <a class="inline_disabled" href="https://www.frontiersin.org/journals/education/articles/10.3389/feduc.2024.1324506/full" target="_blank" rel="noopener">This is what I'm thinking!</a>)</span></p>

<p><strong>LOOK AT ALL THE FILES IN THE HOMEWORK SCAFFOLDS!</strong>&nbsp; I don't drop files into the scaffold github repos to take up room. The support files (anything not named <em>report.qmd</em> or <em>report.html</em>) often provide very useful examples for completing the homework. Why reinvent the wheel!&nbsp; Investigate what I provide and you may find answers to all your questions and SAVE YOU HOURS<span>&trade;.</span></p>

<p><strong>WATCH THE LECTURES!</strong> - It's clear from both the canvas statistics AND the questions I receive on the weekends that over half of you are not watching the lectures. <a class="inline_disabled" title="Link" href="https://www.youtube.com/watch?v=9qdfMYFl0Ic" target="_blank" rel="noopener">Try it - you'll like it!</a>&nbsp; In each lecture I spend time at the beginning talking about the homework assignments, comment on questions I've been receiving from others in the class. Heck, I may even provide a tip or trick that can SAVE YOU HOURS<span>&trade;</span>.</p>
<p>The lectures are organized and follow a specific rhythm - on the first slide I provide announcements AND a list of topics for the lecture.&nbsp; Each topic matches a slide separators in the video - you can fast-forward ahead to find where the topic starts.&nbsp; I try to discuss homeworks at the beginning to make the conversation easier to find.</p>
<p><strong>CHECK OUT THE RESOURCES!</strong> - Each week I spend a lot of time curating <em>the perfect</em> resources for sharing on the weekly frontpage. My goal is to provide informative and sometime entertaining sites and videos that will complement the assignments and lectures.&nbsp; Please spend a few minutes at least scanning them.&nbsp; Again, you might find a tip or trick that can SAVE YOU HOURS<span>&trade;</span> on the homework.</p>
<p><strong>READ THE ANNOUNCEMENTS!</strong> - Please, please, please READ the announcements! If you encounter an issue with the homework, FIRST look at the announcements! My fingers are tired from telling people on Saturday and Sunday nights that the usernames and database names changed to LOWERCASE!&nbsp; Your emails to me suggested that you'd already spent hours trying to get the database to work.&nbsp; A quick read of the announcements may SAVE YOU HOURS<span>&trade;!</span></p>