gantt
    dateFormat YYYY-MM-DD
    axisFormat %b %e
    todayMarker stroke-width:7px,stroke:#FFB300,opacity:0.5

    section ER Models
    ER Models : m1, 2025-01-13, 2025-02-03
    Dis1.ER modeling : milestone, 2025-01-26
    Q1.Entity-relation models : milestone, 2025-01-30
    Srv1.Pre-class survey : milestone, 2025-01-13
    HW1.DE Tool Review : milestone, 2025-01-26
    PQ1.Entity-relation models : milestone, 2025-01-30
    Prj1.Intros : milestone, 2025-01-13
    Prj2.Team formation : milestone, 2025-01-19
    Prj3.Ideation : milestone, 2025-01-21
    Prj4.Video Pitch : milestone, 2025-01-19

    section Relational Alg.
    Relational Alg. : m2, 2025-02-03, 2025-02-17
    Dis2.Relational Alg. : milestone, 2025-02-09
    Q2.Relational Algebra : milestone, 2025-02-13
    HW2.Entity Relation Models : milestone, 2025-02-04
    HW3.Relational Algebra Study Guide : milestone, 2025-02-16
    PQ2.Relational Algebra : milestone, 2025-02-13
    Prj5.Design Documentation : milestone, 2025-02-09

    section Normal forms
    Normal forms : m3, 2025-02-17, 2025-03-03
    Dis3.Normal forms : milestone, 2025-02-23
    PQ3.Analysis and Normal Forms : milestone, 2025-03-06
    Prj6.Docker Scaffold : milestone, 2025-03-02

    section SQL
    SQL : m4, 2025-03-03, 2025-04-14
    Dis4.SQL Basics : milestone, 2025-03-23
    Q3.Analysis and Normal Forms : milestone, 2025-03-06
    Q4.SQL Basics : milestone, 2025-03-27
    HW4.Analysis and Normal Forms : milestone, 2025-03-09
    HW5.Getting started with SQL : milestone, 2025-03-23
    HW6.Constructing a database : milestone, 2025-04-06
    HW7.Joining tables and reporting : milestone, 2025-04-13
    PQ4.SQL Basics : milestone, 2025-03-27
    Prj7.Final Submission : milestone, 2025-03-30

    section Adv. SQL
    Adv. SQL : m6, 2025-04-14, 2025-04-30
    HW8.SQL Funhouse : milestone, 2025-04-20
    HW9.Even more on SQL : milestone, 2025-04-27
    HW10.Course evaluation : milestone, 2025-04-29
