
gantt
    dateFormat  M/DD/YYYY
    axisFormat  %b %e

section Week
    Wk 4 : crit, 2/3/2025, 6d

section Topics
    ER Models : m1, 1/12/2025, 3w
    Rel. Algebra: m4, after m1, 2w
    Normal forms: m5, after m4, 2w
    Break: crit, m8, 3/09/2025, 1w
    SQL : m6, after m5, 5w
    Adv. SQL: m7, after m6, 24d
    Reading Day : crit, m10, 4/30/2025, 1d
    Finals : crit, m9, 5/01/2025, 5d

