---
date: last-modified
title: Week 1 - Details
---

<p class="lead">Welcome to the first week of class.  Ready or not, here we go!</p>

Note that the class consists of two sections - a face-to-face, lecture based section and an on-line, asynchronous section.
The course will be paced to the face-to-face section, focusing on weekly activities.  The lectures will be recorded.

The online, asynchronous students SHOULD DEFINITELY review the lectures. Each will contain good info about the assignments for the week will work.

### Things to do this week!

1. *[Introduce yourself](https://virginiacommonwealth.instructure.com/courses/113813/assignments/1072356){target="_blank"}* - The course will require completion of a team-based semester-long project. Your goal during the first week of the course is to find a partner. It starts with introductions.

1. *[Take the pre-class survey](https://virginiacommonwealth.instructure.com/courses/113813/quizzes/216510){target="blank"}* - I'd like to learn more about the students in my class. Besides the *introduce yourself* stuff from above, I've got a survey with a bunch of questions.
The survey is *graded*. That means that you get credit for completing it.

1. *[Join the course discord](https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-course-discord){target="_blank"}* - Previous
classes appreciated a place to get their questions answered by others in the same class.

1. *[Watch lecture 1](https://virginiacommonwealth.instructure.com/courses/113813/pages/lecture-1-video-2){target="_blank"}* - Of course you'll need to wait until it's released. I'll be covering lots of info about how the class works, grading, and other course mechanics. We'll also start on databases!

2. [Review the assignments](https://virginiacommonwealth.instructure.com/courses/113813/assignments){target="_blank"}. It will be a busy semester and things will jump at you quickly! Here is a [gantt chart of the deliverables](https://lowkeylabs.github.io/cmsc408-course-admin/sp2025/detailed-gantt.html){target="_blank"} so that you can see how they all fit together.

### Check out the course resources

Don't be afraid to explore. Below are a bunch of resources to help get you acclimated. You can look ahead, but please realize that 
until the actual week of the semester, I don't always have all the material together!

<ul class="kl_large_link_grid">
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-course-instructor">About the Instructor</a></li>
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/assignments/syllabus">Course Syllabus</a></li>
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-course-project">Course Project</a></li>
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-student-resources">Student Resources</a></li>
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-canvas-resources)">Canvas Resources</a></li>
<li><a href="https://virginiacommonwealth.instructure.com/courses/113813/pages/resource-save-you-hours)">SAVE YOU HOURS&trade;</a></li>
</ul>

### About this page

This page represents the *frontpage* for every week. The *frontpage* lists the deliverables due this week, provides links
to the lecture slides and video (after it's recorded), and any helpful resources and references.

The *frontpage* presents a set of quick links to any week in the semester, and also highlights the current week. You can always
press *Home* on the top left of the Canvas window to return to the current week's *frontpage*.

Below is a gannt chart that highlights the major topics over time for the course and where we are today. The vertical gold bar
represents today and moves live with the sun.
