project:
  type: website
  output-dir: ../docs/guide

format:
  html:
    toc: true
    css: guide.css
#    theme: cosmo

website:
  title: "CMSC 408 - Databases Study Guide"
  page-navigation: true
  bread-crumbs: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ./er-models/index.qmd
        text: ER Models
        target: "_blank"
      - href: ./relational-models/index.qmd
        text: Relational Models
        target: "_blank"
      - href: about.qmd
        text: About
  sidebar:
    # collapse-level: 1
    contents:
      - section: ER Modeling
        contents:
        - href: ./er-models/overview-of-database-design.qmd
          text: Database Design*
        - href: ./er-models/intro-to-er-models.qmd
          text: Intro to ER models*
        - href: er-models/entities-and-attributes.qmd
          text: Entities and Attributes
        - href: er-models/relationships-and-cardinality.qmd
          text: Relations and Cardinality
        - href: er-models/keys-and-identifiers.qmd
          text: Keys and Identifiers
        - href: er-models/er-diagramming.qmd
          text: ER Diagramming*
        - href: er-models/weak-and-strong-entities.qmd
          text: Weak and Strong Entities*
        - href: er-models/advanced-concepts.qmd
          text: Advanced Concepts
        - href: er-models/best-practices.qmd
          text: Best Practices
        - href: er-models/translating-to-relational-schema.qmd
          text: Translation
      - section: Relational Models
        contents:
        - href: ./relational-models/intro-to-relational-models.qmd
          text: Intro to relational models
        - href: ./relational-models/schemas-and-keys.qmd
          text: Schemas and Keys
        - href: ./relational-models/basic-operations.qmd
          text: Basic Operations*
        - href: ./relational-models/set-operations.qmd
          text: Set Operations*
        - href: ./relational-models/join-operations.qmd
          text: Join Operations*
        - href: ./relational-models/renaming-and-division.qmd
          text: Renaming and Division
        - href: ./relational-models/relational-algebra-vs-sql.qmd
          text: Relational algebra vs SQL
        - href: ./relational-models/advanced-queries.qmd
          text: Advanced Queries
        - href: ./relational-models/practical-applications.qmd
          text: Practical Applications
