project:
  output-dir: ../../docs/fa2025

format:
    html:
        minimal: true
        embed-resources: true
        css: styles.css
        mermaid:
          theme: default
          themeVariables:
            ganttCriticalTaskColor: "#ffaaaa"
            ganttCriticalTaskBorderColor: "#aa0000"
            ganttDoneTaskColor: "#aaffaa"
            ganttDoneTaskBorderColor: "#00aa00"
            ganttActiveTaskColor: "#000000"
            ganttActiveTaskBorderColor: "#0000aa"        

execute:
    echo: false

