gantt
    title Databases FA25
    dateFormat YYYY-MM-DD
    axisFormat %b %e
    todayMarker stroke-width:7px,stroke:#FFB300,opacity:0.5

    section Welcome
    Welcome : m0, 2025-08-18, 2025-08-18

    section Overview
    Overview : m1, 2025-08-18, 2025-08-25
    Srv1.Pre-class survey : milestone, default, 2025-08-21, 0d

    section ER Models
    ER Models : m2, 2025-08-25, 2025-09-08
    PQ1.Entity-relation models : milestone, default, 2025-08-25, 0d
    Dis1.ER modeling : milestone, done, 2025-08-31, 0d
    HW1.DE Tool Review : milestone, active, 2025-08-31, 0d
    Q1.Entity-relation models : milestone, default, 2025-09-01, 0d
    HW2.Entity Relation Models : milestone, active, 2025-09-07, 0d

    section Relational Alg.
    Relational Alg. : m3, 2025-09-08, 2025-09-22
    PQ2.Relational Algebra : milestone, default, 2025-09-08, 0d
    Dis2.Relational Alg. : milestone, done, 2025-09-14, 0d
    Q2.Relational Algebra : milestone, default, 2025-09-15, 0d
    HW3.Modeling Your World : milestone, active, 2025-09-21, 0d

    section Normal forms
    Normal forms : m4, 2025-09-22, 2025-10-06
    PQ3.Analysis and Normal Forms : milestone, default, 2025-09-22, 0d
    Dis3.Normal forms : milestone, done, 2025-09-28, 0d
    Q3.Analysis and Normal Forms : milestone, default, 2025-09-29, 0d
    HW4.Analysis and Normal Forms : milestone, active, 2025-10-05, 0d

    section SQL
    SQL : m5, 2025-10-06, 2025-12-08
    PQ4.SQL Basics : milestone, default, 2025-10-06, 0d
    Q4.SQL Basics : milestone, default, 2025-10-12, 0d
    HW5.Getting started with SQL : milestone, active, 2025-10-12, 0d
    HW6.Constructing a database : milestone, active, 2025-10-19, 0d
    Dis4.SQL Basics : milestone, done, 2025-10-26, 0d
    HW7.Joining tables and reporting : milestone, active, 2025-10-26, 0d
    HW8.SQL Funhouse : milestone, active, 2025-11-02, 0d
    HW9.Even more on SQL : milestone, active, 2025-11-09, 0d
    HW10.More SQL : milestone, active, 2025-11-16, 0d
    HW11.More SQL Again : milestone, active, 2025-11-23, 0d
    HW12.More SQL Again : milestone, active, 2025-12-07, 0d

    section Fall Break
    Fall Break : m6, 2025-11-24, 2025-12-01

    section Finals
    Finals : m7, 2025-12-08, 2025-12-09
    Srv2.Course evaluation : milestone, default, 2025-12-08, 0d
