gantt
    title CMSC-408-901 - DATABASES - Fall 2025
    dateFormat YYYY-MM-DD
    axisFormat %b %e
    todayMarker stroke-width:7px,stroke:#FFB300,opacity:0.5

    section Welcome
    Welcome : m0, 2025-08-18, 2025-08-18

    section ER Models
    ER Models : m1, 2025-08-18, 2025-09-08
    Srv1.Pre-class survey : milestone, 2025-08-21, 0d
    PQ1.Entity-relation models : milestone, 2025-08-27, 0d
    Dis1.ER modeling : milestone, 2025-08-31, 0d
    HW1.DE Tool Review : milestone, 2025-08-31, 0d
    Q1.Entity-relation models : milestone, 2025-09-03, 0d

    section Relational Alg.
    Relational Alg. : m2, 2025-09-08, 2025-09-22
    PQ2.Relational Algebra : milestone, 2025-09-08, 0d
    HW2.Entity Relation Models : milestone, 2025-09-09, 0d
    Dis2.Relational Alg. : milestone, 2025-09-14, 0d
    Q2.Relational Algebra : milestone, 2025-09-17, 0d
    HW3.Modeling Your World : milestone, 2025-09-21, 0d

    section Normal forms
    Normal forms : m3, 2025-09-22, 2025-10-13
    Dis3.Normal forms : milestone, 2025-09-28, 0d
    PQ3.Analysis and Normal Forms : milestone, 2025-09-29, 0d
    Q3.Analysis and Normal Forms : milestone, 2025-10-08, 0d
    HW4.Analysis and Normal Forms : milestone, 2025-10-12, 0d

    section SQL I
    SQL I : m4, 2025-10-13, 2025-11-03
    HW5.Getting started with SQL : milestone, 2025-10-19, 0d
    PQ4.SQL Basics : milestone, 2025-10-20, 0d
    Dis4.SQL Basics : milestone, 2025-10-26, 0d
    HW6.Constructing a database : milestone, 2025-10-26, 0d
    Q4.SQL Basics : milestone, 2025-10-29, 0d

    section SQL II
    SQL II : m5, 2025-11-03, 2025-12-08
    HW7.Joining tables and reporting : milestone, 2025-11-09, 0d
    HW8.SQL Funhouse : milestone, 2025-11-16, 0d
    HW9.Even more on SQL : milestone, 2025-11-23, 0d

    section Fall Break
    Fall Break : m6, 2025-11-24, 2025-12-01

    section Finals
    Finals : m7, 2025-12-08, 2025-12-09
    Srv2.Course evaluation : milestone, 2025-12-03, 0d

    section Semester Project
    Prj1.Intros : milestone, 2025-08-24, 0d
    Prj2.Team formation : milestone, 2025-08-31, 0d
    Prj3.Ideation : milestone, 2025-09-07, 0d
    Prj4.Video Pitch : milestone, 2025-09-14, 0d
    Prj5.Design Documentation : milestone, 2025-10-05, 0d
    Prj6.Docker Scaffold : milestone, 2025-11-02, 0d
    Prj7.Final Submission : milestone, 2025-12-02, 0d
