2025-11-02 08:08:00 | INFO     | Logger initialized at INFO
./grant-db-to-user.sh -u fa25_akkayak -d simpsons_data
./grant-db-to-user.sh -u fa25_lbcarasik -d simpsons_data
./grant-db-to-user.sh -u fa25_tdroper -d simpsons_data
./grant-db-to-user.sh -u fa25_afzalie -d simpsons_data
./grant-db-to-user.sh -u fa25_agyeiyebme -d simpsons_data
./grant-db-to-user.sh -u fa25_alcibars -d simpsons_data
./grant-db-to-user.sh -u fa25_alexanderjl3 -d simpsons_data
./grant-db-to-user.sh -u fa25_almadaniha2 -d simpsons_data
./grant-db-to-user.sh -u fa25_arayaramirfr -d simpsons_data
./grant-db-to-user.sh -u fa25_assefay -d simpsons_data
./grant-db-to-user.sh -u fa25_atajanst -d simpsons_data
./grant-db-to-user.sh -u fa25_bagalace -d simpsons_data
./grant-db-to-user.sh -u fa25_baigm5 -d simpsons_data
./grant-db-to-user.sh -u fa25_baldersonwj -d simpsons_data
./grant-db-to-user.sh -u fa25_bartelsi -d simpsons_data
./grant-db-to-user.sh -u fa25_belkna -d simpsons_data
./grant-db-to-user.sh -u fa25_benabderrazm -d simpsons_data
./grant-db-to-user.sh -u fa25_bergerts -d simpsons_data
./grant-db-to-user.sh -u fa25_bickelag -d simpsons_data
./grant-db-to-user.sh -u fa25_bihiy -d simpsons_data
./grant-db-to-user.sh -u fa25_bilesn -d simpsons_data
./grant-db-to-user.sh -u fa25_blackindl -d simpsons_data
./grant-db-to-user.sh -u fa25_boatengmb -d simpsons_data
./grant-db-to-user.sh -u fa25_bohnc -d simpsons_data
./grant-db-to-user.sh -u fa25_borumea -d simpsons_data
./grant-db-to-user.sh -u fa25_bradyrm -d simpsons_data
./grant-db-to-user.sh -u fa25_britoflorecl -d simpsons_data
./grant-db-to-user.sh -u fa25_burnermb -d simpsons_data
./grant-db-to-user.sh -u fa25_carduckj -d simpsons_data
./grant-db-to-user.sh -u fa25_carrollan -d simpsons_data
./grant-db-to-user.sh -u fa25_castagnolave -d simpsons_data
./grant-db-to-user.sh -u fa25_chalamachars -d simpsons_data
./grant-db-to-user.sh -u fa25_chandk2 -d simpsons_data
./grant-db-to-user.sh -u fa25_chaouljc -d simpsons_data
./grant-db-to-user.sh -u fa25_chaturvedia2 -d simpsons_data
./grant-db-to-user.sh -u fa25_choudaryrh -d simpsons_data
./grant-db-to-user.sh -u fa25_combspalievm -d simpsons_data
./grant-db-to-user.sh -u fa25_davilam -d simpsons_data
./grant-db-to-user.sh -u fa25_delpilargj -d simpsons_data
./grant-db-to-user.sh -u fa25_desaiyp -d simpsons_data
./grant-db-to-user.sh -u fa25_devinesg -d simpsons_data
./grant-db-to-user.sh -u fa25_dhanaliwalas -d simpsons_data
./grant-db-to-user.sh -u fa25_dharamsiss2 -d simpsons_data
./grant-db-to-user.sh -u fa25_dolfir -d simpsons_data
./grant-db-to-user.sh -u fa25_drapergc -d simpsons_data
./grant-db-to-user.sh -u fa25_eatonrm2 -d simpsons_data
./grant-db-to-user.sh -u fa25_ebyt -d simpsons_data
./grant-db-to-user.sh -u fa25_elkaderith -d simpsons_data
./grant-db-to-user.sh -u fa25_elkoam -d simpsons_data
./grant-db-to-user.sh -u fa25_elyj -d simpsons_data
./grant-db-to-user.sh -u fa25_fergusonjc -d simpsons_data
./grant-db-to-user.sh -u fa25_finocchiohl -d simpsons_data
./grant-db-to-user.sh -u fa25_floydes -d simpsons_data
./grant-db-to-user.sh -u fa25_foltyngw -d simpsons_data
./grant-db-to-user.sh -u fa25_fondacoj -d simpsons_data
./grant-db-to-user.sh -u fa25_fondjask -d simpsons_data
./grant-db-to-user.sh -u fa25_friedrichzs -d simpsons_data
./grant-db-to-user.sh -u fa25_ganapathym -d simpsons_data
./grant-db-to-user.sh -u fa25_glassal -d simpsons_data
./grant-db-to-user.sh -u fa25_gonzalezj19 -d simpsons_data
./grant-db-to-user.sh -u fa25_greennj -d simpsons_data
./grant-db-to-user.sh -u fa25_gyawalis3 -d simpsons_data
./grant-db-to-user.sh -u fa25_haledl2 -d simpsons_data
./grant-db-to-user.sh -u fa25_hayesae9 -d simpsons_data
./grant-db-to-user.sh -u fa25_hendersonwj -d simpsons_data
./grant-db-to-user.sh -u fa25_herbstb -d simpsons_data
./grant-db-to-user.sh -u fa25_hodged -d simpsons_data
./grant-db-to-user.sh -u fa25_howkcm -d simpsons_data
./grant-db-to-user.sh -u fa25_huynhkt3 -d simpsons_data
./grant-db-to-user.sh -u fa25_hwangpoks -d simpsons_data
./grant-db-to-user.sh -u fa25_hwangpoky -d simpsons_data
./grant-db-to-user.sh -u fa25_ibrahimar2 -d simpsons_data
./grant-db-to-user.sh -u fa25_jacksonca9 -d simpsons_data
./grant-db-to-user.sh -u fa25_jaghorieh -d simpsons_data
./grant-db-to-user.sh -u fa25_jamess7 -d simpsons_data
./grant-db-to-user.sh -u fa25_jawado -d simpsons_data
./grant-db-to-user.sh -u fa25_jenningsac -d simpsons_data
./grant-db-to-user.sh -u fa25_johnsonbd7 -d simpsons_data
./grant-db-to-user.sh -u fa25_jonesjd12 -d simpsons_data
./grant-db-to-user.sh -u fa25_joshual -d simpsons_data
./grant-db-to-user.sh -u fa25_kayowamm -d simpsons_data
./grant-db-to-user.sh -u fa25_keenholdhc -d simpsons_data
./grant-db-to-user.sh -u fa25_kemmeybg -d simpsons_data
./grant-db-to-user.sh -u fa25_lem5 -d simpsons_data
./grant-db-to-user.sh -u fa25_leej116 -d simpsons_data
./grant-db-to-user.sh -u fa25_leonk2 -d simpsons_data
./grant-db-to-user.sh -u fa25_linjc -d simpsons_data
./grant-db-to-user.sh -u fa25_maazouzrm -d simpsons_data
./grant-db-to-user.sh -u fa25_marshalltl3 -d simpsons_data
./grant-db-to-user.sh -u fa25_mbengueml -d simpsons_data
./grant-db-to-user.sh -u fa25_mcintoshel -d simpsons_data
./grant-db-to-user.sh -u fa25_minkoffjg -d simpsons_data
./grant-db-to-user.sh -u fa25_muletana -d simpsons_data
./grant-db-to-user.sh -u fa25_naimn -d simpsons_data
./grant-db-to-user.sh -u fa25_naphaderh -d simpsons_data
./grant-db-to-user.sh -u fa25_nardic -d simpsons_data
./grant-db-to-user.sh -u fa25_nesmithca -d simpsons_data
./grant-db-to-user.sh -u fa25_nevarezcara -d simpsons_data
./grant-db-to-user.sh -u fa25_nguyennn9 -d simpsons_data
./grant-db-to-user.sh -u fa25_nguyent77 -d simpsons_data
./grant-db-to-user.sh -u fa25_niemeyers -d simpsons_data
./grant-db-to-user.sh -u fa25_obrimahoo -d simpsons_data
./grant-db-to-user.sh -u fa25_ogdenkd -d simpsons_data
./grant-db-to-user.sh -u fa25_oldhamc -d simpsons_data
./grant-db-to-user.sh -u fa25_paraschivv -d simpsons_data
./grant-db-to-user.sh -u fa25_pateliv2 -d simpsons_data
./grant-db-to-user.sh -u fa25_patelk31 -d simpsons_data
./grant-db-to-user.sh -u fa25_patelkn7 -d simpsons_data
./grant-db-to-user.sh -u fa25_pattersona11 -d simpsons_data
./grant-db-to-user.sh -u fa25_piercera -d simpsons_data
./grant-db-to-user.sh -u fa25_pisharodyas2 -d simpsons_data
./grant-db-to-user.sh -u fa25_plumleymg -d simpsons_data
./grant-db-to-user.sh -u fa25_poudeld -d simpsons_data
./grant-db-to-user.sh -u fa25_pradhanr -d simpsons_data
./grant-db-to-user.sh -u fa25_purankaram -d simpsons_data
./grant-db-to-user.sh -u fa25_qasemjs -d simpsons_data
./grant-db-to-user.sh -u fa25_ramseygc -d simpsons_data
./grant-db-to-user.sh -u fa25_raym5 -d simpsons_data
./grant-db-to-user.sh -u fa25_raysj -d simpsons_data
./grant-db-to-user.sh -u fa25_rehmani -d simpsons_data
./grant-db-to-user.sh -u fa25_qbrentz -d simpsons_data
./grant-db-to-user.sh -u fa25_rezah -d simpsons_data
./grant-db-to-user.sh -u fa25_rickstd -d simpsons_data
./grant-db-to-user.sh -u fa25_riveraramosc -d simpsons_data
./grant-db-to-user.sh -u fa25_rodriguesng -d simpsons_data
./grant-db-to-user.sh -u fa25_romande2 -d simpsons_data
./grant-db-to-user.sh -u fa25_rossmj3 -d simpsons_data
./grant-db-to-user.sh -u fa25_rosss11 -d simpsons_data
./grant-db-to-user.sh -u fa25_routhcc -d simpsons_data
./grant-db-to-user.sh -u fa25_salamaa2 -d simpsons_data
./grant-db-to-user.sh -u fa25_salazark -d simpsons_data
./grant-db-to-user.sh -u fa25_salihas -d simpsons_data
./grant-db-to-user.sh -u fa25_samsona3 -d simpsons_data
./grant-db-to-user.sh -u fa25_sanfordac2 -d simpsons_data
./grant-db-to-user.sh -u fa25_saraviaje -d simpsons_data
./grant-db-to-user.sh -u fa25_sazoj -d simpsons_data
./grant-db-to-user.sh -u fa25_sharmar16 -d simpsons_data
./grant-db-to-user.sh -u fa25_siddiqiso -d simpsons_data
./grant-db-to-user.sh -u fa25_silveriocm -d simpsons_data
./grant-db-to-user.sh -u fa25_singhsa4 -d simpsons_data
./grant-db-to-user.sh -u fa25_sonaryd -d simpsons_data
./grant-db-to-user.sh -u fa25_sooranidf -d simpsons_data
./grant-db-to-user.sh -u fa25_sotoh -d simpsons_data
./grant-db-to-user.sh -u fa25_struckcm -d simpsons_data
./grant-db-to-user.sh -u fa25_szafranz -d simpsons_data
./grant-db-to-user.sh -u fa25_tamanga2 -d simpsons_data
./grant-db-to-user.sh -u fa25_teverovskyir -d simpsons_data
./grant-db-to-user.sh -u fa25_thanasackpa -d simpsons_data
./grant-db-to-user.sh -u fa25_trandn3 -d simpsons_data
./grant-db-to-user.sh -u fa25_traversj -d simpsons_data
./grant-db-to-user.sh -u fa25_tuckera5 -d simpsons_data
./grant-db-to-user.sh -u fa25_turnerj20 -d simpsons_data
./grant-db-to-user.sh -u fa25_tyreegm -d simpsons_data
./grant-db-to-user.sh -u fa25_usonn -d simpsons_data
./grant-db-to-user.sh -u fa25_waldenne -d simpsons_data
./grant-db-to-user.sh -u fa25_walkercs -d simpsons_data
./grant-db-to-user.sh -u fa25_wellsmh -d simpsons_data
./grant-db-to-user.sh -u fa25_wheelerbt2 -d simpsons_data
./grant-db-to-user.sh -u fa25_williamsrj -d simpsons_data
./grant-db-to-user.sh -u fa25_wilsonc21 -d simpsons_data
./grant-db-to-user.sh -u fa25_wrighthc2 -d simpsons_data
./grant-db-to-user.sh -u fa25_zhenga6 -d simpsons_data
./grant-db-to-user.sh -u fa25_ayyatma -d simpsons_data
./grant-db-to-user.sh -u fa25_silvasotolr -d simpsons_data
./grant-db-to-user.sh -u fa25_ccbudwell -d simpsons_data
./grant-db-to-user.sh -u fa25_jdleonard -d simpsons_data
