2025-10-01 13:32:43 | INFO     | Logger initialized at INFO
2025-10-01 13:32:43 | INFO     | Shout4_${login_id}_joY
2025-10-01 13:32:43 | INFO     | Shout4_${login_id}_joY
./add-mysql-user-and-db.sh -u fa25_lbcarasik -p Shout4_lbcarasik_joY
./add-mysql-user-and-db.sh -u fa25_tdroper -p Shout4_tdroper_joY
./add-mysql-user-and-db.sh -u fa25_afzalie -p Shout4_afzalie_joY
./add-mysql-user-and-db.sh -u fa25_agyeiyebme -p Shout4_agyeiyebme_joY
./add-mysql-user-and-db.sh -u fa25_alcibars -p Shout4_alcibars_joY
./add-mysql-user-and-db.sh -u fa25_alexanderjl3 -p Shout4_alexanderjl3_joY
./add-mysql-user-and-db.sh -u fa25_almadaniha2 -p Shout4_almadaniha2_joY
./add-mysql-user-and-db.sh -u fa25_arayaramirfr -p Shout4_arayaramirfr_joY
./add-mysql-user-and-db.sh -u fa25_assefay -p Shout4_assefay_joY
./add-mysql-user-and-db.sh -u fa25_atajanst -p Shout4_atajanst_joY
./add-mysql-user-and-db.sh -u fa25_bagalace -p Shout4_bagalace_joY
./add-mysql-user-and-db.sh -u fa25_baigm5 -p Shout4_baigm5_joY
./add-mysql-user-and-db.sh -u fa25_baldersonwj -p Shout4_baldersonwj_joY
./add-mysql-user-and-db.sh -u fa25_bartelsi -p Shout4_bartelsi_joY
./add-mysql-user-and-db.sh -u fa25_belkna -p Shout4_belkna_joY
./add-mysql-user-and-db.sh -u fa25_benabderrazm -p Shout4_benabderrazm_joY
./add-mysql-user-and-db.sh -u fa25_bergerts -p Shout4_bergerts_joY
./add-mysql-user-and-db.sh -u fa25_bickelag -p Shout4_bickelag_joY
./add-mysql-user-and-db.sh -u fa25_bihiy -p Shout4_bihiy_joY
./add-mysql-user-and-db.sh -u fa25_bilesn -p Shout4_bilesn_joY
./add-mysql-user-and-db.sh -u fa25_blackindl -p Shout4_blackindl_joY
./add-mysql-user-and-db.sh -u fa25_boatengmb -p Shout4_boatengmb_joY
./add-mysql-user-and-db.sh -u fa25_bohnc -p Shout4_bohnc_joY
./add-mysql-user-and-db.sh -u fa25_borumea -p Shout4_borumea_joY
./add-mysql-user-and-db.sh -u fa25_bradyrm -p Shout4_bradyrm_joY
./add-mysql-user-and-db.sh -u fa25_britoflorecl -p Shout4_britoflorecl_joY
./add-mysql-user-and-db.sh -u fa25_burnermb -p Shout4_burnermb_joY
./add-mysql-user-and-db.sh -u fa25_carduckj -p Shout4_carduckj_joY
./add-mysql-user-and-db.sh -u fa25_carrollan -p Shout4_carrollan_joY
./add-mysql-user-and-db.sh -u fa25_castagnolave -p Shout4_castagnolave_joY
./add-mysql-user-and-db.sh -u fa25_chalamachars -p Shout4_chalamachars_joY
./add-mysql-user-and-db.sh -u fa25_chandk2 -p Shout4_chandk2_joY
./add-mysql-user-and-db.sh -u fa25_chaouljc -p Shout4_chaouljc_joY
./add-mysql-user-and-db.sh -u fa25_chaturvedia2 -p Shout4_chaturvedia2_joY
./add-mysql-user-and-db.sh -u fa25_choudaryrh -p Shout4_choudaryrh_joY
./add-mysql-user-and-db.sh -u fa25_combspalievm -p Shout4_combspalievm_joY
./add-mysql-user-and-db.sh -u fa25_davilam -p Shout4_davilam_joY
./add-mysql-user-and-db.sh -u fa25_delpilargj -p Shout4_delpilargj_joY
./add-mysql-user-and-db.sh -u fa25_desaiyp -p Shout4_desaiyp_joY
./add-mysql-user-and-db.sh -u fa25_devinesg -p Shout4_devinesg_joY
./add-mysql-user-and-db.sh -u fa25_dhanaliwalas -p Shout4_dhanaliwalas_joY
./add-mysql-user-and-db.sh -u fa25_dharamsiss2 -p Shout4_dharamsiss2_joY
./add-mysql-user-and-db.sh -u fa25_dolfir -p Shout4_dolfir_joY
./add-mysql-user-and-db.sh -u fa25_drapergc -p Shout4_drapergc_joY
./add-mysql-user-and-db.sh -u fa25_eatonrm2 -p Shout4_eatonrm2_joY
./add-mysql-user-and-db.sh -u fa25_ebyt -p Shout4_ebyt_joY
./add-mysql-user-and-db.sh -u fa25_elkaderith -p Shout4_elkaderith_joY
./add-mysql-user-and-db.sh -u fa25_elkoam -p Shout4_elkoam_joY
./add-mysql-user-and-db.sh -u fa25_elyj -p Shout4_elyj_joY
./add-mysql-user-and-db.sh -u fa25_fergusonjc -p Shout4_fergusonjc_joY
./add-mysql-user-and-db.sh -u fa25_finocchiohl -p Shout4_finocchiohl_joY
./add-mysql-user-and-db.sh -u fa25_floydes -p Shout4_floydes_joY
./add-mysql-user-and-db.sh -u fa25_foltyngw -p Shout4_foltyngw_joY
./add-mysql-user-and-db.sh -u fa25_fondacoj -p Shout4_fondacoj_joY
./add-mysql-user-and-db.sh -u fa25_fondjask -p Shout4_fondjask_joY
./add-mysql-user-and-db.sh -u fa25_friedrichzs -p Shout4_friedrichzs_joY
./add-mysql-user-and-db.sh -u fa25_ganapathym -p Shout4_ganapathym_joY
./add-mysql-user-and-db.sh -u fa25_glassal -p Shout4_glassal_joY
./add-mysql-user-and-db.sh -u fa25_gonzalezj19 -p Shout4_gonzalezj19_joY
./add-mysql-user-and-db.sh -u fa25_greennj -p Shout4_greennj_joY
./add-mysql-user-and-db.sh -u fa25_gyawalis3 -p Shout4_gyawalis3_joY
./add-mysql-user-and-db.sh -u fa25_haledl2 -p Shout4_haledl2_joY
./add-mysql-user-and-db.sh -u fa25_hayesae9 -p Shout4_hayesae9_joY
./add-mysql-user-and-db.sh -u fa25_hendersonwj -p Shout4_hendersonwj_joY
./add-mysql-user-and-db.sh -u fa25_herbstb -p Shout4_herbstb_joY
./add-mysql-user-and-db.sh -u fa25_hodged -p Shout4_hodged_joY
./add-mysql-user-and-db.sh -u fa25_howkcm -p Shout4_howkcm_joY
./add-mysql-user-and-db.sh -u fa25_huynhkt3 -p Shout4_huynhkt3_joY
./add-mysql-user-and-db.sh -u fa25_hwangpoks -p Shout4_hwangpoks_joY
./add-mysql-user-and-db.sh -u fa25_hwangpoky -p Shout4_hwangpoky_joY
./add-mysql-user-and-db.sh -u fa25_ibrahimar2 -p Shout4_ibrahimar2_joY
./add-mysql-user-and-db.sh -u fa25_jacksonca9 -p Shout4_jacksonca9_joY
./add-mysql-user-and-db.sh -u fa25_jaghorieh -p Shout4_jaghorieh_joY
./add-mysql-user-and-db.sh -u fa25_jamess7 -p Shout4_jamess7_joY
./add-mysql-user-and-db.sh -u fa25_jawado -p Shout4_jawado_joY
./add-mysql-user-and-db.sh -u fa25_jenningsac -p Shout4_jenningsac_joY
./add-mysql-user-and-db.sh -u fa25_johnsonbd7 -p Shout4_johnsonbd7_joY
./add-mysql-user-and-db.sh -u fa25_jonesjd12 -p Shout4_jonesjd12_joY
./add-mysql-user-and-db.sh -u fa25_joshual -p Shout4_joshual_joY
./add-mysql-user-and-db.sh -u fa25_kayowamm -p Shout4_kayowamm_joY
./add-mysql-user-and-db.sh -u fa25_keenholdhc -p Shout4_keenholdhc_joY
./add-mysql-user-and-db.sh -u fa25_kemmeybg -p Shout4_kemmeybg_joY
./add-mysql-user-and-db.sh -u fa25_lem5 -p Shout4_lem5_joY
./add-mysql-user-and-db.sh -u fa25_leej116 -p Shout4_leej116_joY
./add-mysql-user-and-db.sh -u fa25_leonk2 -p Shout4_leonk2_joY
./add-mysql-user-and-db.sh -u fa25_linjc -p Shout4_linjc_joY
./add-mysql-user-and-db.sh -u fa25_maazouzrm -p Shout4_maazouzrm_joY
./add-mysql-user-and-db.sh -u fa25_marshalltl3 -p Shout4_marshalltl3_joY
./add-mysql-user-and-db.sh -u fa25_mbengueml -p Shout4_mbengueml_joY
./add-mysql-user-and-db.sh -u fa25_mcintoshel -p Shout4_mcintoshel_joY
./add-mysql-user-and-db.sh -u fa25_minkoffjg -p Shout4_minkoffjg_joY
./add-mysql-user-and-db.sh -u fa25_muletana -p Shout4_muletana_joY
./add-mysql-user-and-db.sh -u fa25_naimn -p Shout4_naimn_joY
./add-mysql-user-and-db.sh -u fa25_naphaderh -p Shout4_naphaderh_joY
./add-mysql-user-and-db.sh -u fa25_nardic -p Shout4_nardic_joY
./add-mysql-user-and-db.sh -u fa25_nesmithca -p Shout4_nesmithca_joY
./add-mysql-user-and-db.sh -u fa25_nevarezcara -p Shout4_nevarezcara_joY
./add-mysql-user-and-db.sh -u fa25_nguyennn9 -p Shout4_nguyennn9_joY
./add-mysql-user-and-db.sh -u fa25_nguyent77 -p Shout4_nguyent77_joY
./add-mysql-user-and-db.sh -u fa25_niemeyers -p Shout4_niemeyers_joY
./add-mysql-user-and-db.sh -u fa25_obrimahoo -p Shout4_obrimahoo_joY
./add-mysql-user-and-db.sh -u fa25_ogdenkd -p Shout4_ogdenkd_joY
./add-mysql-user-and-db.sh -u fa25_oldhamc -p Shout4_oldhamc_joY
./add-mysql-user-and-db.sh -u fa25_paraschivv -p Shout4_paraschivv_joY
./add-mysql-user-and-db.sh -u fa25_pateliv2 -p Shout4_pateliv2_joY
./add-mysql-user-and-db.sh -u fa25_patelk31 -p Shout4_patelk31_joY
./add-mysql-user-and-db.sh -u fa25_patelkn7 -p Shout4_patelkn7_joY
./add-mysql-user-and-db.sh -u fa25_pattersona11 -p Shout4_pattersona11_joY
./add-mysql-user-and-db.sh -u fa25_piercera -p Shout4_piercera_joY
./add-mysql-user-and-db.sh -u fa25_pisharodyas2 -p Shout4_pisharodyas2_joY
./add-mysql-user-and-db.sh -u fa25_plumleymg -p Shout4_plumleymg_joY
./add-mysql-user-and-db.sh -u fa25_poudeld -p Shout4_poudeld_joY
./add-mysql-user-and-db.sh -u fa25_pradhanr -p Shout4_pradhanr_joY
./add-mysql-user-and-db.sh -u fa25_purankaram -p Shout4_purankaram_joY
./add-mysql-user-and-db.sh -u fa25_qasemjs -p Shout4_qasemjs_joY
./add-mysql-user-and-db.sh -u fa25_ramseygc -p Shout4_ramseygc_joY
./add-mysql-user-and-db.sh -u fa25_raym5 -p Shout4_raym5_joY
./add-mysql-user-and-db.sh -u fa25_raysj -p Shout4_raysj_joY
./add-mysql-user-and-db.sh -u fa25_rehmani -p Shout4_rehmani_joY
./add-mysql-user-and-db.sh -u fa25_qbrentz -p Shout4_qbrentz_joY
./add-mysql-user-and-db.sh -u fa25_rezah -p Shout4_rezah_joY
./add-mysql-user-and-db.sh -u fa25_rickstd -p Shout4_rickstd_joY
./add-mysql-user-and-db.sh -u fa25_riveraramosc -p Shout4_riveraramosc_joY
./add-mysql-user-and-db.sh -u fa25_rodriguesng -p Shout4_rodriguesng_joY
./add-mysql-user-and-db.sh -u fa25_romande2 -p Shout4_romande2_joY
./add-mysql-user-and-db.sh -u fa25_rossmj3 -p Shout4_rossmj3_joY
./add-mysql-user-and-db.sh -u fa25_rosss11 -p Shout4_rosss11_joY
./add-mysql-user-and-db.sh -u fa25_routhcc -p Shout4_routhcc_joY
./add-mysql-user-and-db.sh -u fa25_salamaa2 -p Shout4_salamaa2_joY
./add-mysql-user-and-db.sh -u fa25_salazark -p Shout4_salazark_joY
./add-mysql-user-and-db.sh -u fa25_salihas -p Shout4_salihas_joY
./add-mysql-user-and-db.sh -u fa25_samsona3 -p Shout4_samsona3_joY
./add-mysql-user-and-db.sh -u fa25_sanfordac2 -p Shout4_sanfordac2_joY
./add-mysql-user-and-db.sh -u fa25_saraviaje -p Shout4_saraviaje_joY
./add-mysql-user-and-db.sh -u fa25_sazoj -p Shout4_sazoj_joY
./add-mysql-user-and-db.sh -u fa25_sharmar16 -p Shout4_sharmar16_joY
./add-mysql-user-and-db.sh -u fa25_siddiqiso -p Shout4_siddiqiso_joY
./add-mysql-user-and-db.sh -u fa25_silveriocm -p Shout4_silveriocm_joY
./add-mysql-user-and-db.sh -u fa25_singhsa4 -p Shout4_singhsa4_joY
./add-mysql-user-and-db.sh -u fa25_sonaryd -p Shout4_sonaryd_joY
./add-mysql-user-and-db.sh -u fa25_sooranidf -p Shout4_sooranidf_joY
./add-mysql-user-and-db.sh -u fa25_sotoh -p Shout4_sotoh_joY
./add-mysql-user-and-db.sh -u fa25_struckcm -p Shout4_struckcm_joY
./add-mysql-user-and-db.sh -u fa25_szafranz -p Shout4_szafranz_joY
./add-mysql-user-and-db.sh -u fa25_tamanga2 -p Shout4_tamanga2_joY
./add-mysql-user-and-db.sh -u fa25_teverovskyir -p Shout4_teverovskyir_joY
./add-mysql-user-and-db.sh -u fa25_thanasackpa -p Shout4_thanasackpa_joY
./add-mysql-user-and-db.sh -u fa25_trandn3 -p Shout4_trandn3_joY
./add-mysql-user-and-db.sh -u fa25_traversj -p Shout4_traversj_joY
./add-mysql-user-and-db.sh -u fa25_tuckera5 -p Shout4_tuckera5_joY
./add-mysql-user-and-db.sh -u fa25_turnerj20 -p Shout4_turnerj20_joY
./add-mysql-user-and-db.sh -u fa25_tyreegm -p Shout4_tyreegm_joY
./add-mysql-user-and-db.sh -u fa25_usonn -p Shout4_usonn_joY
./add-mysql-user-and-db.sh -u fa25_waldenne -p Shout4_waldenne_joY
./add-mysql-user-and-db.sh -u fa25_walkercs -p Shout4_walkercs_joY
./add-mysql-user-and-db.sh -u fa25_wellsmh -p Shout4_wellsmh_joY
./add-mysql-user-and-db.sh -u fa25_wheelerbt2 -p Shout4_wheelerbt2_joY
./add-mysql-user-and-db.sh -u fa25_williamsrj -p Shout4_williamsrj_joY
./add-mysql-user-and-db.sh -u fa25_wilsonc21 -p Shout4_wilsonc21_joY
./add-mysql-user-and-db.sh -u fa25_wrighthc2 -p Shout4_wrighthc2_joY
./add-mysql-user-and-db.sh -u fa25_zhenga6 -p Shout4_zhenga6_joY
./add-mysql-user-and-db.sh -u fa25_ayyatma -p Shout4_ayyatma_joY
./add-mysql-user-and-db.sh -u fa25_silvasotolr -p Shout4_silvasotolr_joY
./add-mysql-user-and-db.sh -u fa25_ccbudwell -p Shout4_ccbudwell_joY
./add-mysql-user-and-db.sh -u fa25_jdleonard -p Shout4_jdleonard_joY
