2025-10-01 13:23:31 | INFO     | Logger initialized at INFO
./add-mysql-db-to-user.sh -u fa25_lbcarasik -d fa25_lbcarasik_hw5
./add-mysql-db-to-user.sh -u fa25_tdroper -d fa25_tdroper_hw5
./add-mysql-db-to-user.sh -u fa25_afzalie -d fa25_afzalie_hw5
./add-mysql-db-to-user.sh -u fa25_agyeiyebme -d fa25_agyeiyebme_hw5
./add-mysql-db-to-user.sh -u fa25_alcibars -d fa25_alcibars_hw5
./add-mysql-db-to-user.sh -u fa25_alexanderjl3 -d fa25_alexanderjl3_hw5
./add-mysql-db-to-user.sh -u fa25_almadaniha2 -d fa25_almadaniha2_hw5
./add-mysql-db-to-user.sh -u fa25_arayaramirfr -d fa25_arayaramirfr_hw5
./add-mysql-db-to-user.sh -u fa25_assefay -d fa25_assefay_hw5
./add-mysql-db-to-user.sh -u fa25_atajanst -d fa25_atajanst_hw5
./add-mysql-db-to-user.sh -u fa25_bagalace -d fa25_bagalace_hw5
./add-mysql-db-to-user.sh -u fa25_baigm5 -d fa25_baigm5_hw5
./add-mysql-db-to-user.sh -u fa25_baldersonwj -d fa25_baldersonwj_hw5
./add-mysql-db-to-user.sh -u fa25_bartelsi -d fa25_bartelsi_hw5
./add-mysql-db-to-user.sh -u fa25_belkna -d fa25_belkna_hw5
./add-mysql-db-to-user.sh -u fa25_benabderrazm -d fa25_benabderrazm_hw5
./add-mysql-db-to-user.sh -u fa25_bergerts -d fa25_bergerts_hw5
./add-mysql-db-to-user.sh -u fa25_bickelag -d fa25_bickelag_hw5
./add-mysql-db-to-user.sh -u fa25_bihiy -d fa25_bihiy_hw5
./add-mysql-db-to-user.sh -u fa25_bilesn -d fa25_bilesn_hw5
./add-mysql-db-to-user.sh -u fa25_blackindl -d fa25_blackindl_hw5
./add-mysql-db-to-user.sh -u fa25_boatengmb -d fa25_boatengmb_hw5
./add-mysql-db-to-user.sh -u fa25_bohnc -d fa25_bohnc_hw5
./add-mysql-db-to-user.sh -u fa25_borumea -d fa25_borumea_hw5
./add-mysql-db-to-user.sh -u fa25_bradyrm -d fa25_bradyrm_hw5
./add-mysql-db-to-user.sh -u fa25_britoflorecl -d fa25_britoflorecl_hw5
./add-mysql-db-to-user.sh -u fa25_burnermb -d fa25_burnermb_hw5
./add-mysql-db-to-user.sh -u fa25_carduckj -d fa25_carduckj_hw5
./add-mysql-db-to-user.sh -u fa25_carrollan -d fa25_carrollan_hw5
./add-mysql-db-to-user.sh -u fa25_castagnolave -d fa25_castagnolave_hw5
./add-mysql-db-to-user.sh -u fa25_chalamachars -d fa25_chalamachars_hw5
./add-mysql-db-to-user.sh -u fa25_chandk2 -d fa25_chandk2_hw5
./add-mysql-db-to-user.sh -u fa25_chaouljc -d fa25_chaouljc_hw5
./add-mysql-db-to-user.sh -u fa25_chaturvedia2 -d fa25_chaturvedia2_hw5
./add-mysql-db-to-user.sh -u fa25_choudaryrh -d fa25_choudaryrh_hw5
./add-mysql-db-to-user.sh -u fa25_combspalievm -d fa25_combspalievm_hw5
./add-mysql-db-to-user.sh -u fa25_davilam -d fa25_davilam_hw5
./add-mysql-db-to-user.sh -u fa25_delpilargj -d fa25_delpilargj_hw5
./add-mysql-db-to-user.sh -u fa25_desaiyp -d fa25_desaiyp_hw5
./add-mysql-db-to-user.sh -u fa25_devinesg -d fa25_devinesg_hw5
./add-mysql-db-to-user.sh -u fa25_dhanaliwalas -d fa25_dhanaliwalas_hw5
./add-mysql-db-to-user.sh -u fa25_dharamsiss2 -d fa25_dharamsiss2_hw5
./add-mysql-db-to-user.sh -u fa25_dolfir -d fa25_dolfir_hw5
./add-mysql-db-to-user.sh -u fa25_drapergc -d fa25_drapergc_hw5
./add-mysql-db-to-user.sh -u fa25_eatonrm2 -d fa25_eatonrm2_hw5
./add-mysql-db-to-user.sh -u fa25_ebyt -d fa25_ebyt_hw5
./add-mysql-db-to-user.sh -u fa25_elkaderith -d fa25_elkaderith_hw5
./add-mysql-db-to-user.sh -u fa25_elkoam -d fa25_elkoam_hw5
./add-mysql-db-to-user.sh -u fa25_elyj -d fa25_elyj_hw5
./add-mysql-db-to-user.sh -u fa25_fergusonjc -d fa25_fergusonjc_hw5
./add-mysql-db-to-user.sh -u fa25_finocchiohl -d fa25_finocchiohl_hw5
./add-mysql-db-to-user.sh -u fa25_floydes -d fa25_floydes_hw5
./add-mysql-db-to-user.sh -u fa25_foltyngw -d fa25_foltyngw_hw5
./add-mysql-db-to-user.sh -u fa25_fondacoj -d fa25_fondacoj_hw5
./add-mysql-db-to-user.sh -u fa25_fondjask -d fa25_fondjask_hw5
./add-mysql-db-to-user.sh -u fa25_friedrichzs -d fa25_friedrichzs_hw5
./add-mysql-db-to-user.sh -u fa25_ganapathym -d fa25_ganapathym_hw5
./add-mysql-db-to-user.sh -u fa25_glassal -d fa25_glassal_hw5
./add-mysql-db-to-user.sh -u fa25_gonzalezj19 -d fa25_gonzalezj19_hw5
./add-mysql-db-to-user.sh -u fa25_greennj -d fa25_greennj_hw5
./add-mysql-db-to-user.sh -u fa25_gyawalis3 -d fa25_gyawalis3_hw5
./add-mysql-db-to-user.sh -u fa25_haledl2 -d fa25_haledl2_hw5
./add-mysql-db-to-user.sh -u fa25_hayesae9 -d fa25_hayesae9_hw5
./add-mysql-db-to-user.sh -u fa25_hendersonwj -d fa25_hendersonwj_hw5
./add-mysql-db-to-user.sh -u fa25_herbstb -d fa25_herbstb_hw5
./add-mysql-db-to-user.sh -u fa25_hodged -d fa25_hodged_hw5
./add-mysql-db-to-user.sh -u fa25_howkcm -d fa25_howkcm_hw5
./add-mysql-db-to-user.sh -u fa25_huynhkt3 -d fa25_huynhkt3_hw5
./add-mysql-db-to-user.sh -u fa25_hwangpoks -d fa25_hwangpoks_hw5
./add-mysql-db-to-user.sh -u fa25_hwangpoky -d fa25_hwangpoky_hw5
./add-mysql-db-to-user.sh -u fa25_ibrahimar2 -d fa25_ibrahimar2_hw5
./add-mysql-db-to-user.sh -u fa25_jacksonca9 -d fa25_jacksonca9_hw5
./add-mysql-db-to-user.sh -u fa25_jaghorieh -d fa25_jaghorieh_hw5
./add-mysql-db-to-user.sh -u fa25_jamess7 -d fa25_jamess7_hw5
./add-mysql-db-to-user.sh -u fa25_jawado -d fa25_jawado_hw5
./add-mysql-db-to-user.sh -u fa25_jenningsac -d fa25_jenningsac_hw5
./add-mysql-db-to-user.sh -u fa25_johnsonbd7 -d fa25_johnsonbd7_hw5
./add-mysql-db-to-user.sh -u fa25_jonesjd12 -d fa25_jonesjd12_hw5
./add-mysql-db-to-user.sh -u fa25_joshual -d fa25_joshual_hw5
./add-mysql-db-to-user.sh -u fa25_kayowamm -d fa25_kayowamm_hw5
./add-mysql-db-to-user.sh -u fa25_keenholdhc -d fa25_keenholdhc_hw5
./add-mysql-db-to-user.sh -u fa25_kemmeybg -d fa25_kemmeybg_hw5
./add-mysql-db-to-user.sh -u fa25_lem5 -d fa25_lem5_hw5
./add-mysql-db-to-user.sh -u fa25_leej116 -d fa25_leej116_hw5
./add-mysql-db-to-user.sh -u fa25_leonk2 -d fa25_leonk2_hw5
./add-mysql-db-to-user.sh -u fa25_linjc -d fa25_linjc_hw5
./add-mysql-db-to-user.sh -u fa25_maazouzrm -d fa25_maazouzrm_hw5
./add-mysql-db-to-user.sh -u fa25_marshalltl3 -d fa25_marshalltl3_hw5
./add-mysql-db-to-user.sh -u fa25_mbengueml -d fa25_mbengueml_hw5
./add-mysql-db-to-user.sh -u fa25_mcintoshel -d fa25_mcintoshel_hw5
./add-mysql-db-to-user.sh -u fa25_minkoffjg -d fa25_minkoffjg_hw5
./add-mysql-db-to-user.sh -u fa25_muletana -d fa25_muletana_hw5
./add-mysql-db-to-user.sh -u fa25_naimn -d fa25_naimn_hw5
./add-mysql-db-to-user.sh -u fa25_naphaderh -d fa25_naphaderh_hw5
./add-mysql-db-to-user.sh -u fa25_nardic -d fa25_nardic_hw5
./add-mysql-db-to-user.sh -u fa25_nesmithca -d fa25_nesmithca_hw5
./add-mysql-db-to-user.sh -u fa25_nevarezcara -d fa25_nevarezcara_hw5
./add-mysql-db-to-user.sh -u fa25_nguyennn9 -d fa25_nguyennn9_hw5
./add-mysql-db-to-user.sh -u fa25_nguyent77 -d fa25_nguyent77_hw5
./add-mysql-db-to-user.sh -u fa25_niemeyers -d fa25_niemeyers_hw5
./add-mysql-db-to-user.sh -u fa25_obrimahoo -d fa25_obrimahoo_hw5
./add-mysql-db-to-user.sh -u fa25_ogdenkd -d fa25_ogdenkd_hw5
./add-mysql-db-to-user.sh -u fa25_oldhamc -d fa25_oldhamc_hw5
./add-mysql-db-to-user.sh -u fa25_paraschivv -d fa25_paraschivv_hw5
./add-mysql-db-to-user.sh -u fa25_pateliv2 -d fa25_pateliv2_hw5
./add-mysql-db-to-user.sh -u fa25_patelk31 -d fa25_patelk31_hw5
./add-mysql-db-to-user.sh -u fa25_patelkn7 -d fa25_patelkn7_hw5
./add-mysql-db-to-user.sh -u fa25_pattersona11 -d fa25_pattersona11_hw5
./add-mysql-db-to-user.sh -u fa25_piercera -d fa25_piercera_hw5
./add-mysql-db-to-user.sh -u fa25_pisharodyas2 -d fa25_pisharodyas2_hw5
./add-mysql-db-to-user.sh -u fa25_plumleymg -d fa25_plumleymg_hw5
./add-mysql-db-to-user.sh -u fa25_poudeld -d fa25_poudeld_hw5
./add-mysql-db-to-user.sh -u fa25_pradhanr -d fa25_pradhanr_hw5
./add-mysql-db-to-user.sh -u fa25_purankaram -d fa25_purankaram_hw5
./add-mysql-db-to-user.sh -u fa25_qasemjs -d fa25_qasemjs_hw5
./add-mysql-db-to-user.sh -u fa25_ramseygc -d fa25_ramseygc_hw5
./add-mysql-db-to-user.sh -u fa25_raym5 -d fa25_raym5_hw5
./add-mysql-db-to-user.sh -u fa25_raysj -d fa25_raysj_hw5
./add-mysql-db-to-user.sh -u fa25_rehmani -d fa25_rehmani_hw5
./add-mysql-db-to-user.sh -u fa25_qbrentz -d fa25_qbrentz_hw5
./add-mysql-db-to-user.sh -u fa25_rezah -d fa25_rezah_hw5
./add-mysql-db-to-user.sh -u fa25_rickstd -d fa25_rickstd_hw5
./add-mysql-db-to-user.sh -u fa25_riveraramosc -d fa25_riveraramosc_hw5
./add-mysql-db-to-user.sh -u fa25_rodriguesng -d fa25_rodriguesng_hw5
./add-mysql-db-to-user.sh -u fa25_romande2 -d fa25_romande2_hw5
./add-mysql-db-to-user.sh -u fa25_rossmj3 -d fa25_rossmj3_hw5
./add-mysql-db-to-user.sh -u fa25_rosss11 -d fa25_rosss11_hw5
./add-mysql-db-to-user.sh -u fa25_routhcc -d fa25_routhcc_hw5
./add-mysql-db-to-user.sh -u fa25_salamaa2 -d fa25_salamaa2_hw5
./add-mysql-db-to-user.sh -u fa25_salazark -d fa25_salazark_hw5
./add-mysql-db-to-user.sh -u fa25_salihas -d fa25_salihas_hw5
./add-mysql-db-to-user.sh -u fa25_samsona3 -d fa25_samsona3_hw5
./add-mysql-db-to-user.sh -u fa25_sanfordac2 -d fa25_sanfordac2_hw5
./add-mysql-db-to-user.sh -u fa25_saraviaje -d fa25_saraviaje_hw5
./add-mysql-db-to-user.sh -u fa25_sazoj -d fa25_sazoj_hw5
./add-mysql-db-to-user.sh -u fa25_sharmar16 -d fa25_sharmar16_hw5
./add-mysql-db-to-user.sh -u fa25_siddiqiso -d fa25_siddiqiso_hw5
./add-mysql-db-to-user.sh -u fa25_silveriocm -d fa25_silveriocm_hw5
./add-mysql-db-to-user.sh -u fa25_singhsa4 -d fa25_singhsa4_hw5
./add-mysql-db-to-user.sh -u fa25_sonaryd -d fa25_sonaryd_hw5
./add-mysql-db-to-user.sh -u fa25_sooranidf -d fa25_sooranidf_hw5
./add-mysql-db-to-user.sh -u fa25_sotoh -d fa25_sotoh_hw5
./add-mysql-db-to-user.sh -u fa25_struckcm -d fa25_struckcm_hw5
./add-mysql-db-to-user.sh -u fa25_szafranz -d fa25_szafranz_hw5
./add-mysql-db-to-user.sh -u fa25_tamanga2 -d fa25_tamanga2_hw5
./add-mysql-db-to-user.sh -u fa25_teverovskyir -d fa25_teverovskyir_hw5
./add-mysql-db-to-user.sh -u fa25_thanasackpa -d fa25_thanasackpa_hw5
./add-mysql-db-to-user.sh -u fa25_trandn3 -d fa25_trandn3_hw5
./add-mysql-db-to-user.sh -u fa25_traversj -d fa25_traversj_hw5
./add-mysql-db-to-user.sh -u fa25_tuckera5 -d fa25_tuckera5_hw5
./add-mysql-db-to-user.sh -u fa25_turnerj20 -d fa25_turnerj20_hw5
./add-mysql-db-to-user.sh -u fa25_tyreegm -d fa25_tyreegm_hw5
./add-mysql-db-to-user.sh -u fa25_usonn -d fa25_usonn_hw5
./add-mysql-db-to-user.sh -u fa25_waldenne -d fa25_waldenne_hw5
./add-mysql-db-to-user.sh -u fa25_walkercs -d fa25_walkercs_hw5
./add-mysql-db-to-user.sh -u fa25_wellsmh -d fa25_wellsmh_hw5
./add-mysql-db-to-user.sh -u fa25_wheelerbt2 -d fa25_wheelerbt2_hw5
./add-mysql-db-to-user.sh -u fa25_williamsrj -d fa25_williamsrj_hw5
./add-mysql-db-to-user.sh -u fa25_wilsonc21 -d fa25_wilsonc21_hw5
./add-mysql-db-to-user.sh -u fa25_wrighthc2 -d fa25_wrighthc2_hw5
./add-mysql-db-to-user.sh -u fa25_zhenga6 -d fa25_zhenga6_hw5
./add-mysql-db-to-user.sh -u fa25_ayyatma -d fa25_ayyatma_hw5
./add-mysql-db-to-user.sh -u fa25_silvasotolr -d fa25_silvasotolr_hw5
./add-mysql-db-to-user.sh -u fa25_ccbudwell -d fa25_ccbudwell_hw5
./add-mysql-db-to-user.sh -u fa25_jdleonard -d fa25_jdleonard_hw5
