2025-11-02 08:05:12 | INFO     | Logger initialized at INFO
./grant-db-to-user.sh -u fa25_akkayak -d world_bank_data
./grant-db-to-user.sh -u fa25_lbcarasik -d world_bank_data
./grant-db-to-user.sh -u fa25_tdroper -d world_bank_data
./grant-db-to-user.sh -u fa25_afzalie -d world_bank_data
./grant-db-to-user.sh -u fa25_agyeiyebme -d world_bank_data
./grant-db-to-user.sh -u fa25_alcibars -d world_bank_data
./grant-db-to-user.sh -u fa25_alexanderjl3 -d world_bank_data
./grant-db-to-user.sh -u fa25_almadaniha2 -d world_bank_data
./grant-db-to-user.sh -u fa25_arayaramirfr -d world_bank_data
./grant-db-to-user.sh -u fa25_assefay -d world_bank_data
./grant-db-to-user.sh -u fa25_atajanst -d world_bank_data
./grant-db-to-user.sh -u fa25_bagalace -d world_bank_data
./grant-db-to-user.sh -u fa25_baigm5 -d world_bank_data
./grant-db-to-user.sh -u fa25_baldersonwj -d world_bank_data
./grant-db-to-user.sh -u fa25_bartelsi -d world_bank_data
./grant-db-to-user.sh -u fa25_belkna -d world_bank_data
./grant-db-to-user.sh -u fa25_benabderrazm -d world_bank_data
./grant-db-to-user.sh -u fa25_bergerts -d world_bank_data
./grant-db-to-user.sh -u fa25_bickelag -d world_bank_data
./grant-db-to-user.sh -u fa25_bihiy -d world_bank_data
./grant-db-to-user.sh -u fa25_bilesn -d world_bank_data
./grant-db-to-user.sh -u fa25_blackindl -d world_bank_data
./grant-db-to-user.sh -u fa25_boatengmb -d world_bank_data
./grant-db-to-user.sh -u fa25_bohnc -d world_bank_data
./grant-db-to-user.sh -u fa25_borumea -d world_bank_data
./grant-db-to-user.sh -u fa25_bradyrm -d world_bank_data
./grant-db-to-user.sh -u fa25_britoflorecl -d world_bank_data
./grant-db-to-user.sh -u fa25_burnermb -d world_bank_data
./grant-db-to-user.sh -u fa25_carduckj -d world_bank_data
./grant-db-to-user.sh -u fa25_carrollan -d world_bank_data
./grant-db-to-user.sh -u fa25_castagnolave -d world_bank_data
./grant-db-to-user.sh -u fa25_chalamachars -d world_bank_data
./grant-db-to-user.sh -u fa25_chandk2 -d world_bank_data
./grant-db-to-user.sh -u fa25_chaouljc -d world_bank_data
./grant-db-to-user.sh -u fa25_chaturvedia2 -d world_bank_data
./grant-db-to-user.sh -u fa25_choudaryrh -d world_bank_data
./grant-db-to-user.sh -u fa25_combspalievm -d world_bank_data
./grant-db-to-user.sh -u fa25_davilam -d world_bank_data
./grant-db-to-user.sh -u fa25_delpilargj -d world_bank_data
./grant-db-to-user.sh -u fa25_desaiyp -d world_bank_data
./grant-db-to-user.sh -u fa25_devinesg -d world_bank_data
./grant-db-to-user.sh -u fa25_dhanaliwalas -d world_bank_data
./grant-db-to-user.sh -u fa25_dharamsiss2 -d world_bank_data
./grant-db-to-user.sh -u fa25_dolfir -d world_bank_data
./grant-db-to-user.sh -u fa25_drapergc -d world_bank_data
./grant-db-to-user.sh -u fa25_eatonrm2 -d world_bank_data
./grant-db-to-user.sh -u fa25_ebyt -d world_bank_data
./grant-db-to-user.sh -u fa25_elkaderith -d world_bank_data
./grant-db-to-user.sh -u fa25_elkoam -d world_bank_data
./grant-db-to-user.sh -u fa25_elyj -d world_bank_data
./grant-db-to-user.sh -u fa25_fergusonjc -d world_bank_data
./grant-db-to-user.sh -u fa25_finocchiohl -d world_bank_data
./grant-db-to-user.sh -u fa25_floydes -d world_bank_data
./grant-db-to-user.sh -u fa25_foltyngw -d world_bank_data
./grant-db-to-user.sh -u fa25_fondacoj -d world_bank_data
./grant-db-to-user.sh -u fa25_fondjask -d world_bank_data
./grant-db-to-user.sh -u fa25_friedrichzs -d world_bank_data
./grant-db-to-user.sh -u fa25_ganapathym -d world_bank_data
./grant-db-to-user.sh -u fa25_glassal -d world_bank_data
./grant-db-to-user.sh -u fa25_gonzalezj19 -d world_bank_data
./grant-db-to-user.sh -u fa25_greennj -d world_bank_data
./grant-db-to-user.sh -u fa25_gyawalis3 -d world_bank_data
./grant-db-to-user.sh -u fa25_haledl2 -d world_bank_data
./grant-db-to-user.sh -u fa25_hayesae9 -d world_bank_data
./grant-db-to-user.sh -u fa25_hendersonwj -d world_bank_data
./grant-db-to-user.sh -u fa25_herbstb -d world_bank_data
./grant-db-to-user.sh -u fa25_hodged -d world_bank_data
./grant-db-to-user.sh -u fa25_howkcm -d world_bank_data
./grant-db-to-user.sh -u fa25_huynhkt3 -d world_bank_data
./grant-db-to-user.sh -u fa25_hwangpoks -d world_bank_data
./grant-db-to-user.sh -u fa25_hwangpoky -d world_bank_data
./grant-db-to-user.sh -u fa25_ibrahimar2 -d world_bank_data
./grant-db-to-user.sh -u fa25_jacksonca9 -d world_bank_data
./grant-db-to-user.sh -u fa25_jaghorieh -d world_bank_data
./grant-db-to-user.sh -u fa25_jamess7 -d world_bank_data
./grant-db-to-user.sh -u fa25_jawado -d world_bank_data
./grant-db-to-user.sh -u fa25_jenningsac -d world_bank_data
./grant-db-to-user.sh -u fa25_johnsonbd7 -d world_bank_data
./grant-db-to-user.sh -u fa25_jonesjd12 -d world_bank_data
./grant-db-to-user.sh -u fa25_joshual -d world_bank_data
./grant-db-to-user.sh -u fa25_kayowamm -d world_bank_data
./grant-db-to-user.sh -u fa25_keenholdhc -d world_bank_data
./grant-db-to-user.sh -u fa25_kemmeybg -d world_bank_data
./grant-db-to-user.sh -u fa25_lem5 -d world_bank_data
./grant-db-to-user.sh -u fa25_leej116 -d world_bank_data
./grant-db-to-user.sh -u fa25_leonk2 -d world_bank_data
./grant-db-to-user.sh -u fa25_linjc -d world_bank_data
./grant-db-to-user.sh -u fa25_maazouzrm -d world_bank_data
./grant-db-to-user.sh -u fa25_marshalltl3 -d world_bank_data
./grant-db-to-user.sh -u fa25_mbengueml -d world_bank_data
./grant-db-to-user.sh -u fa25_mcintoshel -d world_bank_data
./grant-db-to-user.sh -u fa25_minkoffjg -d world_bank_data
./grant-db-to-user.sh -u fa25_muletana -d world_bank_data
./grant-db-to-user.sh -u fa25_naimn -d world_bank_data
./grant-db-to-user.sh -u fa25_naphaderh -d world_bank_data
./grant-db-to-user.sh -u fa25_nardic -d world_bank_data
./grant-db-to-user.sh -u fa25_nesmithca -d world_bank_data
./grant-db-to-user.sh -u fa25_nevarezcara -d world_bank_data
./grant-db-to-user.sh -u fa25_nguyennn9 -d world_bank_data
./grant-db-to-user.sh -u fa25_nguyent77 -d world_bank_data
./grant-db-to-user.sh -u fa25_niemeyers -d world_bank_data
./grant-db-to-user.sh -u fa25_obrimahoo -d world_bank_data
./grant-db-to-user.sh -u fa25_ogdenkd -d world_bank_data
./grant-db-to-user.sh -u fa25_oldhamc -d world_bank_data
./grant-db-to-user.sh -u fa25_paraschivv -d world_bank_data
./grant-db-to-user.sh -u fa25_pateliv2 -d world_bank_data
./grant-db-to-user.sh -u fa25_patelk31 -d world_bank_data
./grant-db-to-user.sh -u fa25_patelkn7 -d world_bank_data
./grant-db-to-user.sh -u fa25_pattersona11 -d world_bank_data
./grant-db-to-user.sh -u fa25_piercera -d world_bank_data
./grant-db-to-user.sh -u fa25_pisharodyas2 -d world_bank_data
./grant-db-to-user.sh -u fa25_plumleymg -d world_bank_data
./grant-db-to-user.sh -u fa25_poudeld -d world_bank_data
./grant-db-to-user.sh -u fa25_pradhanr -d world_bank_data
./grant-db-to-user.sh -u fa25_purankaram -d world_bank_data
./grant-db-to-user.sh -u fa25_qasemjs -d world_bank_data
./grant-db-to-user.sh -u fa25_ramseygc -d world_bank_data
./grant-db-to-user.sh -u fa25_raym5 -d world_bank_data
./grant-db-to-user.sh -u fa25_raysj -d world_bank_data
./grant-db-to-user.sh -u fa25_rehmani -d world_bank_data
./grant-db-to-user.sh -u fa25_qbrentz -d world_bank_data
./grant-db-to-user.sh -u fa25_rezah -d world_bank_data
./grant-db-to-user.sh -u fa25_rickstd -d world_bank_data
./grant-db-to-user.sh -u fa25_riveraramosc -d world_bank_data
./grant-db-to-user.sh -u fa25_rodriguesng -d world_bank_data
./grant-db-to-user.sh -u fa25_romande2 -d world_bank_data
./grant-db-to-user.sh -u fa25_rossmj3 -d world_bank_data
./grant-db-to-user.sh -u fa25_rosss11 -d world_bank_data
./grant-db-to-user.sh -u fa25_routhcc -d world_bank_data
./grant-db-to-user.sh -u fa25_salamaa2 -d world_bank_data
./grant-db-to-user.sh -u fa25_salazark -d world_bank_data
./grant-db-to-user.sh -u fa25_salihas -d world_bank_data
./grant-db-to-user.sh -u fa25_samsona3 -d world_bank_data
./grant-db-to-user.sh -u fa25_sanfordac2 -d world_bank_data
./grant-db-to-user.sh -u fa25_saraviaje -d world_bank_data
./grant-db-to-user.sh -u fa25_sazoj -d world_bank_data
./grant-db-to-user.sh -u fa25_sharmar16 -d world_bank_data
./grant-db-to-user.sh -u fa25_siddiqiso -d world_bank_data
./grant-db-to-user.sh -u fa25_silveriocm -d world_bank_data
./grant-db-to-user.sh -u fa25_singhsa4 -d world_bank_data
./grant-db-to-user.sh -u fa25_sonaryd -d world_bank_data
./grant-db-to-user.sh -u fa25_sooranidf -d world_bank_data
./grant-db-to-user.sh -u fa25_sotoh -d world_bank_data
./grant-db-to-user.sh -u fa25_struckcm -d world_bank_data
./grant-db-to-user.sh -u fa25_szafranz -d world_bank_data
./grant-db-to-user.sh -u fa25_tamanga2 -d world_bank_data
./grant-db-to-user.sh -u fa25_teverovskyir -d world_bank_data
./grant-db-to-user.sh -u fa25_thanasackpa -d world_bank_data
./grant-db-to-user.sh -u fa25_trandn3 -d world_bank_data
./grant-db-to-user.sh -u fa25_traversj -d world_bank_data
./grant-db-to-user.sh -u fa25_tuckera5 -d world_bank_data
./grant-db-to-user.sh -u fa25_turnerj20 -d world_bank_data
./grant-db-to-user.sh -u fa25_tyreegm -d world_bank_data
./grant-db-to-user.sh -u fa25_usonn -d world_bank_data
./grant-db-to-user.sh -u fa25_waldenne -d world_bank_data
./grant-db-to-user.sh -u fa25_walkercs -d world_bank_data
./grant-db-to-user.sh -u fa25_wellsmh -d world_bank_data
./grant-db-to-user.sh -u fa25_wheelerbt2 -d world_bank_data
./grant-db-to-user.sh -u fa25_williamsrj -d world_bank_data
./grant-db-to-user.sh -u fa25_wilsonc21 -d world_bank_data
./grant-db-to-user.sh -u fa25_wrighthc2 -d world_bank_data
./grant-db-to-user.sh -u fa25_zhenga6 -d world_bank_data
./grant-db-to-user.sh -u fa25_ayyatma -d world_bank_data
./grant-db-to-user.sh -u fa25_silvasotolr -d world_bank_data
./grant-db-to-user.sh -u fa25_ccbudwell -d world_bank_data
./grant-db-to-user.sh -u fa25_jdleonard -d world_bank_data
