./add-groupdb-and-user.sh -g sp25_ctrlaltelite -u sp25_acostas
./add-groupdb-and-user.sh -g sp25_entergalactic_coders -u sp25_adepojus
./add-groupdb-and-user.sh -g sp25_na -u sp25_akeredolunr
./add-groupdb-and-user.sh -g sp25_team_arceus -u sp25_amjadm2
./add-groupdb-and-user.sh -g sp25_team_umizumi -u sp25_arbietot
./add-groupdb-and-user.sh -g sp25_minion -u sp25_ayanoug
./add-groupdb-and-user.sh -g sp25_secondhand_friends -u sp25_bahlouly
./add-groupdb-and-user.sh -g sp25_team_arceus -u sp25_behboudin
./add-groupdb-and-user.sh -g sp25_team_dc -u sp25_berdeguezcm
./add-groupdb-and-user.sh -g sp25_team_crusaders -u sp25_biguvubs
./add-groupdb-and-user.sh -g sp25_team_crusaders -u sp25_biguvuhs
./add-groupdb-and-user.sh -g sp25_data_trio -u sp25_bohnc
./add-groupdb-and-user.sh -g sp25_relational_rebels -u sp25_bottuaj2
./add-groupdb-and-user.sh -g sp25_random_word_generators -u sp25_boyettja
./add-groupdb-and-user.sh -g sp25_data_knights -u sp25_chalises2
./add-groupdb-and-user.sh -g sp25_team_awesome -u sp25_chavdarovig
./add-groupdb-and-user.sh -g sp25_database_fc -u sp25_chavezci
./add-groupdb-and-user.sh -g sp25_bookworms -u sp25_clarkl3
./add-groupdb-and-user.sh -g sp25_entergalactic_coders -u sp25_colonca2
./add-groupdb-and-user.sh -g sp25_open_valve -u sp25_corcorantj
./add-groupdb-and-user.sh -g sp25_minion -u sp25_dsouzanb
./add-groupdb-and-user.sh -g sp25_camboviet -u sp25_dangct3
./add-groupdb-and-user.sh -g sp25_data_demons -u sp25_dannoufja
./add-groupdb-and-user.sh -g sp25_schema_squad -u sp25_davisar
./add-groupdb-and-user.sh -g sp25_data_legends -u sp25_davispn6
./add-groupdb-and-user.sh -g sp25_team_umizumi -u sp25_delapenajd
./add-groupdb-and-user.sh -g sp25_cloud_navigators -u sp25_dhanaliwalas
./add-groupdb-and-user.sh -g sp25_code_crusaders -u sp25_dhorajiap
./add-groupdb-and-user.sh -g sp25_strikers -u sp25_duncand3
./add-groupdb-and-user.sh -g sp25_ctrlaltelite -u sp25_duncanrm2
./add-groupdb-and-user.sh -g sp25_millionaire_minions -u sp25_elnafemr
./add-groupdb-and-user.sh -g sp25_goobers -u sp25_essexjg
./add-groupdb-and-user.sh -g sp25_g&c -u sp25_faircw
./add-groupdb-and-user.sh -g sp25_schema_squad -u sp25_fergusonba
./add-groupdb-and-user.sh -g sp25_data_dynamos -u sp25_ganeshr
./add-groupdb-and-user.sh -g sp25_random_word_generators -u sp25_ginthersg
./add-groupdb-and-user.sh -g sp25_ag -u sp25_glassal
./add-groupdb-and-user.sh -g sp25_monkey_munchers -u sp25_govila
./add-groupdb-and-user.sh -g sp25_goobers -u sp25_grayjl3
./add-groupdb-and-user.sh -g sp25_camboviet -u sp25_hayt2
./add-groupdb-and-user.sh -g sp25_relational_rebels -u sp25_hendersonks
./add-groupdb-and-user.sh -g sp25_g&c -u sp25_henrygm
./add-groupdb-and-user.sh -g sp25_data_trio -u sp25_hicksm5
./add-groupdb-and-user.sh -g sp25_binary_brains -u sp25_jalili
./add-groupdb-and-user.sh -g sp25_sj -u sp25_jamess7
./add-groupdb-and-user.sh -g sp25_millionaire_minions -u sp25_jeffreym2
./add-groupdb-and-user.sh -g sp25_secondhand_friends -u sp25_joneskl12
./add-groupdb-and-user.sh -g sp25_database_fc -u sp25_khanr15
./add-groupdb-and-user.sh -g sp25_the_triangles -u sp25_leecl5
./add-groupdb-and-user.sh -g sp25_code_crusaders -u sp25_luchsingerkr
./add-groupdb-and-user.sh -g sp25_binary_brains -u sp25_maazouzrm
./add-groupdb-and-user.sh -g sp25_byte_sized_bandits -u sp25_macklr
./add-groupdb-and-user.sh -g sp25_data_trio -u sp25_maliki3
./add-groupdb-and-user.sh -g sp25_408_crew -u sp25_marandinalc
./add-groupdb-and-user.sh -g sp25_fulcrum -u sp25_meersohnf
./add-groupdb-and-user.sh -g sp25_warriors_of_bytes -u sp25_menendezrd
./add-groupdb-and-user.sh -g sp25_buff_and_bumble -u sp25_mensahko
./add-groupdb-and-user.sh -g sp25_warriors_of_bytes -u sp25_minora3
./add-groupdb-and-user.sh -g sp25_monkey_munchers -u sp25_mohapatraa
./add-groupdb-and-user.sh -g sp25_a-squared -u sp25_nalavadeaa
./add-groupdb-and-user.sh -g sp25_408_crew -u sp25_onyedekek
./add-groupdb-and-user.sh -g sp25_cloud_navigators -u sp25_othmanb
./add-groupdb-and-user.sh -g sp25_a-squared -u sp25_pantigozocam
./add-groupdb-and-user.sh -g sp25_minion -u sp25_phuthongthiak
./add-groupdb-and-user.sh -g sp25_data_dynamos -u sp25_pomeroyjd
./add-groupdb-and-user.sh -g sp25_fulcrum -u sp25_rahmana17
./add-groupdb-and-user.sh -g sp25_random_word_generators -u sp25_raphaelke
./add-groupdb-and-user.sh -g sp25_buff_and_bumble -u sp25_qbrentz
./add-groupdb-and-user.sh -g sp25_team_dc -u sp25_riveradr
./add-groupdb-and-user.sh -g sp25_schema_squad -u sp25_robertj
./add-groupdb-and-user.sh -g sp25_open_valve -u sp25_rutanj
./add-groupdb-and-user.sh -g sp25_as -u sp25_salihas
./add-groupdb-and-user.sh -g sp25_warriors_of_bytes -u sp25_sapptc
./add-groupdb-and-user.sh -g sp25_strikers -u sp25_sarkermm
./add-groupdb-and-user.sh -g sp25_data_demons -u sp25_selbdm
./add-groupdb-and-user.sh -g sp25_data_knights -u sp25_siddiqiso2
./add-groupdb-and-user.sh -g sp25_data_legends -u sp25_singhj21
./add-groupdb-and-user.sh -g sp25_static_duo -u sp25_skeetej
./add-groupdb-and-user.sh -g sp25_asm -u sp25_smithaa9
./add-groupdb-and-user.sh -g sp25_big_stink -u sp25_stephensj4
./add-groupdb-and-user.sh -g sp25_monacan_chiefs -u sp25_strobelb2
./add-groupdb-and-user.sh -g sp25_strikers -u sp25_taylors
./add-groupdb-and-user.sh -g sp25_mt -u sp25_tejedamr
./add-groupdb-and-user.sh -g sp25_monacan_chiefs -u sp25_thompsone7
./add-groupdb-and-user.sh -g sp25_408_crew -u sp25_torresc6
./add-groupdb-and-user.sh -g sp25_dt -u sp25_trand15
./add-groupdb-and-user.sh -g sp25_bookworms -u sp25_trant14
./add-groupdb-and-user.sh -g sp25_the_triangles -u sp25_upadhyaya
./add-groupdb-and-user.sh -g sp25_team_arceus -u sp25_vangipurapus
./add-groupdb-and-user.sh -g sp25_goobers -u sp25_veasnadt
./add-groupdb-and-user.sh -g sp25_the_triangles -u sp25_venkateswarkm
./add-groupdb-and-user.sh -g sp25_static_duo -u sp25_viadolm
./add-groupdb-and-user.sh -g sp25_team_awesome -u sp25_weaverge
./add-groupdb-and-user.sh -g sp25_data_knights -u sp25_wellsmh
./add-groupdb-and-user.sh -g sp25_byte_sized_bandits -u sp25_wilkinsonla
./add-groupdb-and-user.sh -g sp25_millionaire_minions -u sp25_williamsc45
./add-groupdb-and-user.sh -g sp25_the_optimizers -u sp25_winsorlm
./add-groupdb-and-user.sh -g sp25_entergalactic_coders -u sp25_yahayay
./add-groupdb-and-user.sh -g sp25_the_optimizers -u sp25_yazbeckn
