./remove-user-and-db.sh -u sp25_acostas
./remove-user-and-db.sh -u sp25_adepojus
./remove-user-and-db.sh -u sp25_akeredolunr
./remove-user-and-db.sh -u sp25_amjadm2
./remove-user-and-db.sh -u sp25_arbietot
./remove-user-and-db.sh -u sp25_ayanoug
./remove-user-and-db.sh -u sp25_bahlouly
./remove-user-and-db.sh -u sp25_behboudin
./remove-user-and-db.sh -u sp25_berdeguezcm
./remove-user-and-db.sh -u sp25_biguvubs
./remove-user-and-db.sh -u sp25_biguvuhs
./remove-user-and-db.sh -u sp25_bohnc
./remove-user-and-db.sh -u sp25_bottuaj2
./remove-user-and-db.sh -u sp25_boyettja
./remove-user-and-db.sh -u sp25_chalises2
./remove-user-and-db.sh -u sp25_chavdarovig
./remove-user-and-db.sh -u sp25_chavezci
./remove-user-and-db.sh -u sp25_clarkl3
./remove-user-and-db.sh -u sp25_colonca2
./remove-user-and-db.sh -u sp25_corcorantj
./remove-user-and-db.sh -u sp25_dsouzanb
./remove-user-and-db.sh -u sp25_dangct3
./remove-user-and-db.sh -u sp25_dannoufja
./remove-user-and-db.sh -u sp25_davisar
./remove-user-and-db.sh -u sp25_davispn6
./remove-user-and-db.sh -u sp25_delapenajd
./remove-user-and-db.sh -u sp25_dhanaliwalas
./remove-user-and-db.sh -u sp25_dhorajiap
./remove-user-and-db.sh -u sp25_duncand3
./remove-user-and-db.sh -u sp25_duncanrm2
./remove-user-and-db.sh -u sp25_elnafemr
./remove-user-and-db.sh -u sp25_essexjg
./remove-user-and-db.sh -u sp25_faircw
./remove-user-and-db.sh -u sp25_fergusonba
./remove-user-and-db.sh -u sp25_ganeshr
./remove-user-and-db.sh -u sp25_ginthersg
./remove-user-and-db.sh -u sp25_glassal
./remove-user-and-db.sh -u sp25_govila
./remove-user-and-db.sh -u sp25_grayjl3
./remove-user-and-db.sh -u sp25_hayt2
./remove-user-and-db.sh -u sp25_hendersonks
./remove-user-and-db.sh -u sp25_henrygm
./remove-user-and-db.sh -u sp25_hicksm5
./remove-user-and-db.sh -u sp25_jalili
./remove-user-and-db.sh -u sp25_jamess7
./remove-user-and-db.sh -u sp25_jeffreym2
./remove-user-and-db.sh -u sp25_joneskl12
./remove-user-and-db.sh -u sp25_khanr15
./remove-user-and-db.sh -u sp25_leecl5
./remove-user-and-db.sh -u sp25_luchsingerkr
./remove-user-and-db.sh -u sp25_maazouzrm
./remove-user-and-db.sh -u sp25_macklr
./remove-user-and-db.sh -u sp25_maliki3
./remove-user-and-db.sh -u sp25_marandinalc
./remove-user-and-db.sh -u sp25_meersohnf
./remove-user-and-db.sh -u sp25_menendezrd
./remove-user-and-db.sh -u sp25_mensahko
./remove-user-and-db.sh -u sp25_minora3
./remove-user-and-db.sh -u sp25_mohapatraa
./remove-user-and-db.sh -u sp25_nalavadeaa
./remove-user-and-db.sh -u sp25_onyedekek
./remove-user-and-db.sh -u sp25_othmanb
./remove-user-and-db.sh -u sp25_pantigozocam
./remove-user-and-db.sh -u sp25_phuthongthiak
./remove-user-and-db.sh -u sp25_pomeroyjd
./remove-user-and-db.sh -u sp25_rahmana17
./remove-user-and-db.sh -u sp25_raphaelke
./remove-user-and-db.sh -u sp25_qbrentz
./remove-user-and-db.sh -u sp25_riveradr
./remove-user-and-db.sh -u sp25_robertj
./remove-user-and-db.sh -u sp25_rutanj
./remove-user-and-db.sh -u sp25_salihas
./remove-user-and-db.sh -u sp25_sapptc
./remove-user-and-db.sh -u sp25_sarkermm
./remove-user-and-db.sh -u sp25_selbdm
./remove-user-and-db.sh -u sp25_siddiqiso2
./remove-user-and-db.sh -u sp25_singhj21
./remove-user-and-db.sh -u sp25_skeetej
./remove-user-and-db.sh -u sp25_smithaa9
./remove-user-and-db.sh -u sp25_stephensj4
./remove-user-and-db.sh -u sp25_strobelb2
./remove-user-and-db.sh -u sp25_taylors
./remove-user-and-db.sh -u sp25_tejedamr
./remove-user-and-db.sh -u sp25_thompsone7
./remove-user-and-db.sh -u sp25_torresc6
./remove-user-and-db.sh -u sp25_trand15
./remove-user-and-db.sh -u sp25_trant14
./remove-user-and-db.sh -u sp25_upadhyaya
./remove-user-and-db.sh -u sp25_vangipurapus
./remove-user-and-db.sh -u sp25_veasnadt
./remove-user-and-db.sh -u sp25_venkateswarkm
./remove-user-and-db.sh -u sp25_viadolm
./remove-user-and-db.sh -u sp25_weaverge
./remove-user-and-db.sh -u sp25_wellsmh
./remove-user-and-db.sh -u sp25_wilkinsonla
./remove-user-and-db.sh -u sp25_williamsc45
./remove-user-and-db.sh -u sp25_winsorlm
./remove-user-and-db.sh -u sp25_yahayay
./remove-user-and-db.sh -u sp25_yazbeckn
