
    gantt
        dateFormat  M/DD/YYYY
        axisFormat  %W

        section    
        Wk 3 : crit, weekblock, 1/21/2024, 1w

        section Topics
        ER Models : m1, 1/7/2024, 3w
        Rel. Algebra: m4, after m1, 2w
        Normal forms: m5, after m4, 3w
        SQL : m6, after m5, 4w
        Adv. SQL: m7, after m6, 5w
    